### ISSUE TITLE
Custom Formulas for Wild Magic Surge

### ISSUE THREAD

**Issue by SabreRunner** [trioderegion/dnd5e-helpers#104]
Can you add custom formulas for Wild Magic surge so I can choose myself how it's handled?
For example, if I want a d30 < 10 for regular roll or d20 <= spell level + 1d10 for a Tides of Chaos used roll.

**Comment by trioderegion** [comment]
This is a reasonable generalization of the growing number of homebrews we support. I like the idea :)
