### ISSUE TITLE
[Bug] Disabling Action Status Automation option causes permanent action bar above token

### ISSUE THREAD

**Issue by NateHawk85** [trioderegion/dnd5e-helpers#105]
Whenever there is no action status automation enabled, starting combat with a token selected will cause the action bar to pop up over the token and become unable to dismiss. This persists even after the token is deselected, but for screenshot purposes, I figured I'd show what it looks like normally.

![image](https://user-images.githubusercontent.com/7596412/118691283-8821e200-b7ce-11eb-92f4-6b03e9d34101.png)

In order to resolve this issue, the user needs to refresh their browser window.

Versions:
D&D5e --> v1.2.4
DnD5e Helpers --> v2.0.1 (replicated in v2.0.0 as well)

Steps to reproduce:
1) Disable all other modules
2) Adjust the settings so that Combat Helpers --> Action Status Automation --> None
3) Add token(s) to combat tracker
4) With the token(s) still selected, hit the "Begin Combat" button

**Comment by kandashi** [comment]
Ill close this an track through #106
