### ISSUE TITLE
[Feature Request] Add an option to disable the action bar and associated features

### ISSUE THREAD

**Issue by NateHawk85** [trioderegion/dnd5e-helpers#106]
Add an option to disable the action bar completely, removing both the action bar and the action options

![image](https://user-images.githubusercontent.com/7596412/118691853-18f8bd80-b7cf-11eb-870a-3ef96d1bbe97.png)

**Comment by kandashi** [comment]
Oh, it appears I didnt harden the checks for that enough. It shouldnt appear if the setting is disabled

**Comment by trioderegion** [comment]
Enable/Disable of this feature should work much more smoothly in 2.0.2
