### ISSUE TITLE
[Bug] Undead Fortitude settings do not calculate correctly

### ISSUE THREAD

**Issue by NateHawk85** [trioderegion/dnd5e-helpers#107]
Undead Fortitude settings (both Quick Saves and Advanced Saves) do not take additional damage into consideration when calculating if the undead survives or not.

![image](https://user-images.githubusercontent.com/7596412/118693779-01223900-b7d1-11eb-9639-2ca5c9e48e0a.png)

Versions:
D&D5e --> v1.2.4
DnD5e Helpers --> v2.0.1 (replicated in v2.0.0 as well)

Steps to reproduce:

1) Adjust the settings so that Combat Helpers --> Undead Fortitude --> Either Quick Saves or Advanced Saves
2) Deal 99 damage to a token
3) Select "Normal Damage"
4) If the roll is >5, the token will save and remove the "Dead" condition
5) If the roll is <5, the token will fail and persist the "Dead" condition

![Undead Fortitude](https://user-images.githubusercontent.com/7596412/118693547-c4564200-b7d0-11eb-92a1-4e07f6a22fd3.gif)

**Comment by kandashi** [comment]
I cannot repeat this with *just* dnd5e helpers enabled, please try to replicate with only this module enabled, or turn on and check the debug messages

**Comment by NateHawk85** [comment]
1) Disabled all but DnD5e helpers and Find the Culprit! (in order to disable all other modules and retain settings)
2) Enabled System Helpers --> Debugging
3) Set Combat Helpers --> Undead Fortitude to Advanced Saves
4) Added Zombie to Combat Tracker via dragging actor (also replicated by dragging via compendium) and began combat
5) Right clicked on Zombie and set the HP field to -99
6) Clicked "Normal Damage" when prompted
7) Clicked "Normal" when Constitution Saving Throw was prompted
8) Popup displayed as follows:
![image](https://user-images.githubusercontent.com/7596412/119058108-5ad26100-b993-11eb-9bb2-08365b7c601d.png)
9) Zombie was left with 1 hp: 
![image](https://user-images.githubusercontent.com/7596412/119058126-62920580-b993-11eb-8bf9-16eb937dbead.png)

The debug messages in the console were as follows: 
Foundry VTT | Rendering TokenHUD
dnd5e-helpers.js:675 Dnd5e Helpers: Zombie's update contains hp: 0, and Fort: true
foundry.js:4503 Foundry VTT | Rendering Dialog
foundry.js:4503 Foundry VTT | Rendering Dialog
dnd5e-helpers.js:2097 Dnd5e helpers: Could not find an active combat
dnd5e-helpers.js:675 Dnd5e Helpers: Zombie's update contains hp: 1, and Fort: true
foundry.js:29510 Foundry VTT | Created ChatMessage with id VlyGOpldXNyVa9Jr

![Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application and 5 more pages - Personal - Microsoft_ Edge 2021-05-20 17-50-55](https://user-images.githubusercontent.com/7596412/119058569-404cb780-b994-11eb-9158-f7b07724d424.gif)

**Comment by NateHawk85** [comment]
My apologies. It looks as though the issue doesn't persist when just using D&D5e helpers. I'll look into it further. Sorry about that!

**Comment by NateHawk85** [comment]
Ahhhh. Okay. It looks as though it works as intended if the zombie dies to a single strike. However, if the zombie takes damage THEN takes damage again, it bases the damage off the base DC of 5.

1) Disabled all modules except D&D5e helpers and Find the Culprit! (to help disable other modules)
2) Enabled Debug setting and set Undead Fortitude to Quick Saves
3) Set Zombie constitution to have +30 to CON saves (for testing purposes and to get the GIF more consistently :) )
4) Added Zombie to scene
5) Dealt 22 damage to zombie
6) Clicked "Normal Damage" when prompted
7) Clicked "Normal" when prompted for CON save
8) Zombie rolled 33, saving the DC of 28, and returning to 1 HP.
9) Dealt -999 damage to zombie
10) Clicked "Normal Damage" when prompted
11) Clicked "Normal" when prompted for CON save
12) Zombie rolled 48, failing the DC of 1004. Yet, the zombie still returned to 1 HP

![Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application and 5 more pages - Personal - Microsoft_ Edge 2021-05-20 18-17-16](https://user-images.githubusercontent.com/7596412/119060891-c10db280-b998-11eb-97d6-7cd9a75d57c8.gif)


Please nerf this zombie. He TPKed my party and took over their castle.

**Comment by kandashi** [comment]
You are misunderstanding how the quick saves work. It can only read the total hp change, not any excess (as in the documentation).

You will need the advanced saves for more complex stuff like that
