### ISSUE TITLE
[Bug] Action status automation does not work with the Cautious Gamemaster module

### ISSUE THREAD

**Issue by NateHawk85** [trioderegion/dnd5e-helpers#108]
Action status automation does not automate any action/bonus action/reaction effects when used with Cautious Gamemaster v0.1.6.

Versions:
D&D5e --> v1.2.4
DnD5e Helpers --> v2.0.1 (replicated in v2.0.0 as well)

Steps to reproduce:
1) Adjust the settings so that Combat Helpers --> Action Status Automation --> Enabled
2) Add PC and NPC tokens to combat encounter
3) Roll all initiatives
4) Begin encounter
5) On the NPC's turn (Zombie), use an NPC Action (Slam). This will not affect the "Action" section of the action bar
6) On the PC's turn, use an NPC Action (Slam). This will not affect the "Reaction" section of the action bar
7) On the PC's turn, us a PC Action (Sickle). This will not affect the "Action" section of the action bar
8) On the PC's turn, use a PC Bonus Action Spell (Healing Word). This will not affect the "Bonus Action" section of the action bar
9) On the PC's turn, use a PC Bonus Action Feature (Spirit Totem). This will not affect the "Bonus Action" section of the action bar
10) On the NPC's turn (Goblin), use an NPC Bonus Action (Nimble Escape). This will not affect the "Bonus Action" section of the action bar

In previous versions (v1.10.3), this worked alongside Cautious Gamemaster without issues.

**Comment by kandashi** [comment]
I cannot replicate this with just these to modules installed. Can you try to locate any error message in the console, and try with just these two enabled

**Comment by kandashi** [comment]
Im going to close this as no further information was provided
