### ISSUE TITLE
Settings changes for Combat Helpers not being recorded

### ISSUE THREAD

**Issue by AdamSturge** [trioderegion/dnd5e-helpers#109]
I've tried turning on "Lair Action Prompt" and "Legendary Action Prompt" then going to "Save Changes" at the bottom. I'm on Forge so the webpage refreshed. Yet when I check the settings afterwards those options remain unchecked

**Comment by trioderegion** [comment]
Try re-saving them a couple of times. I've noticed this as well. Sorry for the troubles.

**Comment by trioderegion** [comment]
Should be fixed in the 2.0.2 release.
