### ISSUE TITLE
Request: Keep the old Used Reaction Condition

### ISSUE THREAD

**Issue by RavenknightDM** [trioderegion/dnd5e-helpers#110]
Hiya, could we add an option to keep the old Used Reaction condition and skip the new UI-stuff? 
Edit: My players found the new added hud too intrusive and complained a lot during the last session. The added condition for Reaction was perfect for our games since all we really need to know is if a creature has spent their reaction or not.
(I hope that I don't come of as sounding ungrateful, it's a great mod. The hud is just not for us.)

**Comment by trioderegion** [comment]
A compromise has been added to 2.0.2. The HUD will still show, but when a reaction is used, it will add a status effect icon.
