### ISSUE TITLE
Fix the cover message to not be always send to all players

### ISSUE THREAD

**Issue by szefo09** [trioderegion/dnd5e-helpers#112]
https://github.com/trioderegion/dnd5e-helpers/blob/0766155617081e8aa7893bd243169dea5af94613/scripts/dnd5e-helpers.js#L2593
The check for GM user makes it false for all other connected users, which causes the whisper to be sent to everyone, and causes errors when players clicks on wrong message.

**Comment by trioderegion** [comment]
Closed via merge
