### ISSUE TITLE
Error in console 

### ISSUE THREAD

**Issue by Tyreal74** [trioderegion/dnd5e-helpers#113]
Uncaught (in promise) TypeError: Cannot destructure property 'action' of 'usedActions' as it is undefined.
    at Function.actionDialog (dnd5e-helpers.js:2279)
    at HTMLDivElement.<anonymous> (dnd5e-helpers.js:2273)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)

**Comment by trioderegion** [comment]
Can we get a bit more information on what you were doing when this error occurred?

**Comment by Tyreal74** [comment]
I blame kandashi he said to just post it, give me some time I'm not at home illl try to reproduce

**Comment by kandashi** [comment]
sorry, i just asked Tryeal to throw this up and then promptly forgot about it,

**Comment by trioderegion** [comment]
Will need a refresh of this issue if it still exists. Please test again in 2.0.6.
