### ISSUE TITLE
Module does not seem to work with 0.7.10

### ISSUE THREAD

**Issue by deraviin** [trioderegion/dnd5e-helpers#119]
Noticed first with Wild Magic Surge, but reaction automation does not seem to work either. I tested in current game with only Find the Culprit and dnd5e Helpers active and was still unable to get wild magic rolling to work.

To double check I also made a new world and created a wild magic sorcerer in the world. The only module I activated was dnd5e helpers, and then made sure to turn ON the wild magic helper. Created a wild magic rolltable and set all that up etc etc, and still was unable to get it to work. Foundry 0.7.10 and dnd5e version 1.2.4, module version 2.0.3

**Comment by kandashi** [comment]
Did you activate Wild Magic in the Actors special traits menu?

**Comment by deraviin** [comment]
I do have it turned on, and the character has wild magic in their passive abilities.
![0a389cd505954fd902b7d46b57a267ec](https://user-images.githubusercontent.com/46595619/120136949-896cea80-c190-11eb-8ec7-3a20c1f1c5bf.png)
![646eb1b2d4324168742211f4554eef55](https://user-images.githubusercontent.com/46595619/120136956-8a9e1780-c190-11eb-8f4d-f3cc4db929d9.png)

**Comment by trioderegion** [comment]
v2.0 had a paradigm shift for wild magic and I should have made better note of it.

However, the Wild Magic feature marker now lives in the actor's "Special Traits" and does not key off of a wild magic feature item anymore.

**Comment by deraviin** [comment]
I have to admit I'm a bit lost then. Is that an active effect I need to make? Either way it seems clear this is my user error, I'll either figure it out or switch to the other wild magic module. Thanks for your time.

**Comment by trioderegion** [comment]
I'll be sure the readme gets updated with better information.

In the mean-time. On the first tab of the core 5e sheet (abilities), at the bottom right, there is a grey cog labeled "Special Traits". Click that cog to open an menu and a little less than halfway down, there will be a checkbox for "wild magic surge". This will enable wild magic detection for that actor.
