### ISSUE TITLE
Reaction Removal does not find CUB status effects

### ISSUE THREAD

**Issue by kandashi** [trioderegion/dnd5e-helpers#12]
the status effects added by CUB have the prefix combat-utility-belt which prevents them being identified in the line 437

`const existing = currentToken.actor.effects.find(e => e.getFlag("core", "statusId") === statusEffect.id);`

**Comment by trioderegion** [comment]
CUB prefixes the conditions for its own use.

I need to either implicitly test for "conditionA" and "combat-utility-belt.conditionA"
or
note in the readme of this requirement if using CUB.

Need to confirm that this is what is happening first.

**Comment by trioderegion** [comment]
quick first pass by checking 'statusName' and 'combat-utility-belt.statusName'.  Going to leave this open for further compatibility issues with CUB statuses.

**Comment by trioderegion** [comment]
Closing this for now. So far so good.
