### ISSUE TITLE
.8 test issues

### ISSUE THREAD

**Issue by evilcj925** [trioderegion/dnd5e-helpers#121]
Tested on win self host, 8.6 and 1.3.3 dnd5e, accessed through web browser. Midi-Qol, DAE, libwrapper, and socketlib installed. run with debug mode on 

![modules](https://user-images.githubusercontent.com/67852506/120906896-09240a80-c612-11eb-819a-ee50d456b89b.PNG)

1. Auto Proficiency: Tested with Dagger pulled from srd. tested with customer "Dagger" prof marked on actor, than with "simple melee" marked, removing dagger in-between.   Neither marked weapon as prof
2. Wild Magic Surge: works as expected but with hidden results check in settings still shows to player. 
3. Remove targeting after turn: errors in the console. see photo
![target](https://user-images.githubusercontent.com/67852506/120906895-06c1b080-c612-11eb-9e4a-de0483f0cf76.PNG)
4. Action, Reaction Tracking: hud not updating when actions taken. errors in the console.
![action tracking](https://user-images.githubusercontent.com/67852506/120906897-0aedce00-c612-11eb-9719-58d36865608c.PNG)
5. Cover Sytem: message when turn ends after cover is applied. Had a strange error where it said cover effect lasted for two turns on the actors effect tab. After first time, could not get error to repeat. 
![cover system](https://user-images.githubusercontent.com/67852506/120906969-88b1d980-c612-11eb-9936-2d955b2a040b.PNG)

**Comment by trioderegion** [comment]
Thanks a bunch for the report. Will work through them.

Ive gotten (5) a couple times myself, but during a totally different activity. Unsure what's going on exactly, but it does stop firing after a while for me too...

**Comment by trioderegion** [comment]
All but (2) should be addressed in 2.0.4. 

(2) will be addressed at a later date.
