### ISSUE TITLE
Question: how to mark sharpshooter?

### ISSUE THREAD

**Issue by TheRarita** [trioderegion/dnd5e-helpers#125]
In module description you say:

- A new special trait has been added to indicate if the actor should ignore cover (e.g. Sharpshooter or Spell Sniper)
- Alternatively, a flag of "dnd5e", "helpersIgnoreCover" will flags the token as ignoring cover, for use with Spell Sniper or Sharpshooter ( will also remove melee cover effects ).

Where do find this new special trait or how do I apply it? Or how do I apply these flags?
Thanks

**Comment by trioderegion** [comment]
The special traits dialog of your actor (attributes page, bottom right, little grey cog). About halfway down there is a "ignores half and three-quarters cover" checkbox.
