### ISSUE TITLE
Are there known compatibility issues?

### ISSUE THREAD

**Issue by MrManlyMan** [trioderegion/dnd5e-helpers#128]
Are there any known compatibility issues with other modules? Because I cannot interact with 5e helpers in any way. Neither the cover system works, nor the wild magic, nor anything else.

**Comment by kandashi** [comment]
Nothing we know about no. Check your console log, and make sure you are following the instructions to get the functions you expect

**Comment by MrManlyMan** [comment]
Thanks for the information. I disabled most modules now and it seems to be working, but might as well have been a setting issue. I'll need to do some testing after properly setting up the module. My main issue right now is the wild magic. The way I understand it an actor simply needs to have a feature named "Wild Magic Surge" and that should automatically trigger a d20 roll on spell slot reduction which isn't happening for me. Am I doing something wrong? Does the feature need a specific setup?

**Comment by MrManlyMan** [comment]
Thanks a lot! That was the confusion all along. The special traits option is hidden quite away and I was constantly thinking in "feats". 
Might I suggest you add a brief explanation in the settings for Feature Helpers?
Something like:
"In order for this function to work you need to enagle Wild Magic Surge in the Special Traits option of the Character Attributes tab (below proficiencies)". Or a slightly more detailed explanation in the read me.
Because I somehow doubt that I am going to be the last person to be somewhat confused by the wild magic surge setting :)
And now that it's working I gotta say it's a great quality of life module. Great work!

**Comment by trioderegion** [comment]
I 100% need to do another pass on the ReadMe and its on my list. Glad we got you up and running!
