### ISSUE TITLE
Enhancement Request: When "Suppressed" mode is in use, hide token HUD icon

### ISSUE THREAD

**Issue by M0nk3yy** [trioderegion/dnd5e-helpers#133]
When Action Status Automation is set to "Enabled (Display Suppressed)", the token HUD element still shows.

![image](https://user-images.githubusercontent.com/66137312/121915057-c2799300-cd2a-11eb-9be3-a0f53e72d082.png)

I would suggest hiding all added UI elements with this setting.

**Comment by trioderegion** [comment]
This has been added in v3

![image](https://user-images.githubusercontent.com/14878515/131268692-73a87679-d155-4dcc-a0bb-aedb5bfa5aa4.png)
