### ISSUE TITLE
Bug - in create Itens

### ISSUE THREAD

**Issue by rinnocenti** [trioderegion/dnd5e-helpers#134]
![image](https://user-images.githubusercontent.com/3178127/121949868-5e0d0280-cd2f-11eb-826e-a52f50d88ad6.png)
bugs in start-up (on create new itens whit AE)

**Comment by trioderegion** [comment]
Thanks for the notice. Just creating an item throws this error. It is a simple fix and will be rolled into the next release. It should not impact anything negatively (other than the annoying error), but let me know if it does and I will escalate a fix.

Noting this for later

line 718 should read:
```
if (game.settings.get('dnd5e-helpers', 'autoProf') && (item.parent?.data.type === "character")) {
```

**Comment by trioderegion** [comment]
Auto proficiency has been removed in v3 as it will be integrated into core soon(ish)
