### ISSUE TITLE
Ability to ignore Dead/0HP Tokens for Cover Calculation

### ISSUE THREAD

**Issue by giogreymon** [trioderegion/dnd5e-helpers#135]
It would be great to have the ability to recognize if a token is marked Dead or is at 0 hp so they wont be considered in the automatic cover calculation!

**Comment by trioderegion** [comment]
`Token#setCoverValue(Number)` where Number is [0,3] has been exposed in v3 and should be able to be integrated with other "on death" effects.

The final decision was to leave this up to the user as some larger creature may still provide cover when dead or prone.
