### ISSUE TITLE
[Enhancement] Action Bar above darkness/vision/fog of war

### ISSUE THREAD

**Issue by Juanfrank** [trioderegion/dnd5e-helpers#137]
Hello.-

Currently the action bar is rendered below the darkness and/or vision and/or fog of war layer, in such a way that a token without vision on the northern part of the token isn't able to see the bar because the darkness obstructs it. Similarly, a token without vision is unable to see the bar.

Is there any possibility of rendering the action bar above or independent of the token vision in such a way that it doesn't get obstructed by any of the canvas elements (namely darkness/fow)?

Thanks!

**Comment by kandashi** [comment]
This is not possible im afraid. The icon is directly part of the token image, and therefore is rendered as the token is rendered. Changing this would be very complex
