### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by akrigline** [trioderegion/dnd5e-helpers#138]
Is there an open source license noted somewhere I am not finding for this repository? If this code is [all rights reserved](https://choosealicense.com/no-permission/) (as implied by having no license) it makes it difficult to reference for other modules looking to do similar-but-different mechanisms. It also makes it questionable to contribute to.

---

If this isn't intended to be All Rights Reserved, unfortunately since there are so many contributors, [the process is complicated](https://opensource.stackexchange.com/questions/33/how-can-a-project-be-relicensed).

The League is currently going through a similar process with [Forien's Quest Log](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/pull/43).

**Comment by kandashi** [comment]
I dont *believe* it was meant as All Rights Reserved. I thought @trioderegion and I intended it as MIT.

**Comment by trioderegion** [comment]
I'll review the license options and put a proper one in. Just one of those topics that sit on the backburner until it comes up, ya know?

Thanks for bringing it up!

**Comment by trioderegion** [comment]
Progress on licensing can be found in #145 . The pointer to the FQL's process was very helpful, thanks @akrigline . Closing this issue.
