### ISSUE TITLE
Player cover check does not appear to DM

### ISSUE THREAD

**Issue by SR5060** [trioderegion/dnd5e-helpers#139]
haven't tested this extensively but we experienced an issue where the player cover checks did not appear on the DM chat. This is problematic if cover is applied manually (as the DM can't set the manual setting)

**Comment by trioderegion** [comment]
Can you provide any further information on this? I have not seen this occur myself.

**Comment by SR5060** [comment]
I will keep an eye out for it, but it's been so long and I don't recall seeing it lately so we can close for now
