### ISSUE TITLE
Weakened status getting applied out of combat.

### ISSUE THREAD

**Issue by Nedrapter** [trioderegion/dnd5e-helpers#14]
As I was setting up spells and attacks on character sheets, I was testing if the macros/settings are working correctly. Noticed that on every cast/attack (there was no combat) character was getting Weakened status for every attempt of roll. I was told on Foundry discord that this is a feature of the module when actors do things out of their turn. But there was no combat in my case.

**Comment by Nedrapter** [comment]
Also in the settings of the module, Reaction status Automation was set to : None

**Comment by trioderegion** [comment]
Thank you for the report. We are looking into it.

**Comment by kandashi** [comment]
This should solve that issue

**Comment by trioderegion** [comment]
Indeed it does. In 1.5.2.
