### ISSUE TITLE
Cover "bug"

### ISSUE THREAD

**Issue by Fridan99** [trioderegion/dnd5e-helpers#140]
Foundry vtt 0.8.7
Dnd5e helpers 2.0.6

There is an error in the cover calculation

The drow target other token with a straight line WITHOUT obstacles
<img width="606" alt="screenshot1" src="https://user-images.githubusercontent.com/86131373/122617783-cbe56100-d084-11eb-84d1-89b71268c03a.png">

The token conflict is the 3rd
<img width="286" alt="screenshot2" src="https://user-images.githubusercontent.com/86131373/122617960-2d0d3480-d085-11eb-8fd8-e63d7a3d7e0a.png">

Even if I move them away, it still gives wrong result, therefore it is not because of the adjacent 3rd token
<img width="631" alt="screenshot4" src="https://user-images.githubusercontent.com/86131373/122617977-3a2a2380-d085-11eb-8972-b64d3681c6d5.png">

Grid scene and Dnd5e helpers (options, configure into dmg 5e cover calculation)
![screenshot3](https://user-images.githubusercontent.com/86131373/122618146-8ecd9e80-d085-11eb-9ed4-3fd02b80dad0.png)
![screenshot5](https://user-images.githubusercontent.com/86131373/122618153-91c88f00-d085-11eb-83b6-b54ca0a530e1.png)

**Comment by trioderegion** [comment]
This should be addressed in the upcoming rework of the cover calculator. Sorry for the delay, but it will be worth it.

**Comment by Fridan99** [comment]
> This should be addressed in the upcoming rework of the cover calculator. Sorry for the delay, but it will be worth it.

in 2.0.9?

**Comment by trioderegion** [comment]
Short of a critical bug found elsewhere, it will be included in the next release -- not sure of the version number yet. Our replacement system works really well, but it will still be several weeks before its published.

Hang in there <3

**Comment by trioderegion** [comment]
v3 addresses this bug.
