### ISSUE TITLE
Wild Magic Surge checks not happening

### ISSUE THREAD

**Issue by vtt-lair** [trioderegion/dnd5e-helpers#141]
I see the check for wildMagic currently looks at flags in dnd5e.

`const wmActorEnable = actor.getFlag('dnd5e', 'wildMagic')`

However, if I look at the actor flags, the actor does not have a wildMagic flag in dnd5e. Any idea how to check my actor's data to figure out why it's not there?
![image](https://user-images.githubusercontent.com/33215552/122621303-68affa80-d095-11eb-9c94-24c29ce2bf8e.png)

**Comment by trioderegion** [comment]
The flag is controlled by the corresponding option in Special Traits for the actor. I'll be updating the ReadMe to make the process more clear.

**Comment by vtt-lair** [comment]
Thanks @trioderegion. I'm not finding the Special Traits for the actor (I'm probably being an idiot and missing it). A quick Google also doesn't point me in the correct direction.

Where do I access the Special Traits for the actor?

**Comment by vtt-lair** [comment]
I'm blind... found it!
