### ISSUE TITLE
Strengthen detection of desired chat cards

### ISSUE THREAD

**Issue by trioderegion** [trioderegion/dnd5e-helpers#143]
In an effort to reduce error spam with unrecognized chat card types (midi and the like). Try to more gracefully bail out of reaction detection.

Example error:
![image](https://user-images.githubusercontent.com/14878515/122678243-ecf89f80-d1b3-11eb-8e82-22ae7babf24c.png)

**Comment by kandashi** [comment]
This happens with Midi QoL, which passes actor/token ID's rather than the entire object.

**Comment by trioderegion** [comment]
Need to check the status of this one.

**Comment by trioderegion** [comment]
Closing this out as it is a v2 bug. Will confirm in #132 for v3.
