### ISSUE TITLE
[Bug] Two rolls on open wound

### ISSUE THREAD

**Issue by PaulWRoberts** [trioderegion/dnd5e-helpers#148]
Foundry Version 0.8.7
DnD 5e Version 1.3.6
dnd5e helpers Version 2.0.7
Other modules [none]

If I set the open wound to trigger when hp reaches 0 and I update the hp to 0 directly on the token, there are 2 output messages and 2 rolls on the open wound table. If I update the health directly on the character sheet this does not happen.

**Comment by trioderegion** [comment]
quick update: there appears to be a bug in 0.8.8 that is causing some hooks to fire twice when updating a token's hp or other bar attribute.

I'm exploring workarounds.

**Comment by kandashi** [comment]
This is a core issue that will be fixed in 0.8.9, im afraid you'll have to put up with this mini-bug for now
