### ISSUE TITLE
Feature Request: Ignore cover computations/message when on melee combat

### ISSUE THREAD

**Issue by Juanfrank** [trioderegion/dnd5e-helpers#150]
Hello.-

Is there any possibility of adding an optional or mandatory setting whereby the cover computations (and the corresponding chat output) are done **only** when the distance to the target exceeds 5ft? As you may know, there is no cover for melee combat, and there's hardly any way for a creature or object to be in-between when there's no space between them, if using a ranged weapon in melee distance.

**Comment by kandashi** [comment]
Actually, you still get cover in melee. If you want to ignore this, simply dont hold the hotkey when targeting


5e rules for cover don't mention melee/ ranged at all
Walls, trees, creatures, and other obstacles can provide cover during combat, making a target more difficult to harm. A target can benefit from cover only when an attack or other effect originates on the opposite side of the cover.
There are three degrees of cover. If a target is behind multiple sources of cover, only the most protective degree of cover applies; the degrees aren't added together. For example, if a target is behind a creature that gives half cover and a tree trunk that gives three-quarters cover, the target has three-quarters cover.

**Comment by Juanfrank** [comment]
Fair enough. Thanks.
