### ISSUE TITLE
Feature Request: Pack Tactics

### ISSUE THREAD

**Issue by napolitanod** [trioderegion/dnd5e-helpers#152]
Pack tactics: granting advantage on roll if an ally is within 5 feet. This is a difficult thing to automate (kind of a reverse aura) and would be cool if dnd5e helpers could infer this. 

Thanks for your work! I love the cover, recharge and legendary functionality!

**Comment by trioderegion** [comment]
This is a bit outside the scope of 5e Helpers. The biggest issue being that there is no way to automate adv/disadv in the core system.

This *may* be better suited for Active-Auras, maybe.

Thank you for your support though <3 it means a lot.
