### ISSUE TITLE
Cover helper: Melee and ranged diagonal attacks give cover

### ISSUE THREAD

**Issue by gravagehulk** [trioderegion/dnd5e-helpers#155]
Foundry 0.8.8
DnD5e 1.3.6
Module 2.0.8

I can't seem to find a way to fix this or turn it off. The cover helper is awesome and mostly works well, but the one issue I'm having is that when a player is shooting diagonally, even if there's no token or terrain intervening, it gives half cover. This is also true for melee, which should never be the case. When I hover over the cover, it shows that the token next to the target is providing that cover.

Is this a bug? Or is there some setting I'm not using right? I'd love to have the cover be completely automated, but this makes it hard deal with. 

Edit: I just saw issue #140 "Cover Bug". That's exactly what I'm experiencing. Sorry for the duplicate report. I see that you are reworking cover. It can't come soon enough for my group.

**Comment by trioderegion** [comment]
You can still have cover for a melee attack, so that part is working as intended. Development is going to speed back up in the coming weeks and we will have a full rework that addresses this bug.  Sorry for the troubles you are having at the moment.

**Comment by gravagehulk** [comment]
> You can still have cover for a melee attack, so that part is working as intended. Development is going to speed back up in the coming weeks and we will have a full rework that addresses this bug. Sorry for the troubles you are having at the moment.

Sorry, I'm not sure I understand you comment. 50% of the problem I'm having now is that melee cover is not working properly. If a player attacks an enemy standing next to another token, that other token provides cover and it should not. Screenshot for example. Being within 5 feet of a target does not grant cover from melee attacks in 5e.

In the below example, the Tortle is attacking the Giant Centipede (crosshairs). The system thinks that the character north of her is providing half cover because she's attacking diagonally. If I move her directly below the centipede, there is no cover. I tried both DMG rules and Foundry line of sight rules and get the same results. This seems to only happen when attacking diagonally.

![image](https://user-images.githubusercontent.com/69117052/126800045-8c0c4579-45aa-4a18-bc47-ac88ae582800.png)

**Comment by trioderegion** [comment]
Two different issues here :)

1) There is a bug in the current cover calculator that is causing nearby tokens to provide cover when they should not.
2) When I say that melee attacks can still suffer from cover, I mean that cover is computed the same regardless of ranged or melee in the DMG. Oddly shaped walls and narrow doorways could do this, for example.

Your screenshot is highlighting a current bug (1) and will be addressed so that this arrangement does *not* provide half cover to your target -- the bottom right corner of the selected token has full visibility to your target.

**Comment by gravagehulk** [comment]
> Two different issues here :)
> 
> 1. There is a bug in the current cover calculator that is causing nearby tokens to provide cover when they should not.
> 2. When I say that melee attacks can still suffer from cover, I mean that cover is computed the same regardless of ranged or melee in the DMG. Oddly shaped walls and narrow doorways could do this, for example.
> 
> Your screenshot is highlighting a current bug (1) and will be addressed so that this arrangement does _not_ provide half cover to your target -- the bottom right corner of the selected token has full visibility to your target.

Ah, thank you for the clarification, sir. I do appreciate all of your hard work on this module. It has become essential to my games. Looking forward to the next release!

**Comment by trioderegion** [comment]
Issue (1) has been addressed directly in v3.0.0.
