### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by Zarhog** [trioderegion/dnd5e-helpers#156]
![image](https://user-images.githubusercontent.com/76391362/126812797-04487baf-b47e-4b39-9e93-d7232c75530f.png)

Issue 1: Wonds table not working correctly, it dose detect that a character or creature has been damaged correctly, however with NPC it seems to have some save assigned to it for no reason, 

Issue 2: Wonds table no longer seems to roll after clicking roll button even though name is correct in table.

Issue 3: Zombies undead fortitude is calculated wrong with automation and dose not take into account the -5 to the roll that it should

**Comment by kandashi** [comment]
1) the save is following the dmg rules. Refer to that for the full usage. 

2) for players they are prompted to roll after the GM confirms, this must be done on their client

3) the auto fortitude check iant 100% accurate as we cannot read over spill damage. Use the slow check for more accuracy
