### ISSUE TITLE
[Feature] Use "check for cover" key also for targeting

### ISSUE THREAD

**Issue by tagnullde** [trioderegion/dnd5e-helpers#158]
Please add either or both options for these use cases:

- Use "check for cover" key to automaticaly targets the token aswell.
Idea is: If I want to check for cover, I probably want to target the token too.

- add a option similar to "T is for Target". 
This way there is no need to install a seperate module just for targeting. It also should prevent incompatibilities between modules.

Thank you :)

**Comment by thatlonelybugbear** [comment]
Intergrading a choice to assign a keystroke to targeting would be great!

**Comment by trioderegion** [comment]
Will be addressed with #230
