### ISSUE TITLE
Suggestion: cover with prone, unconcious or 0hp creature

### ISSUE THREAD

**Issue by Fridan99** [trioderegion/dnd5e-helpers#160]
It would be nice to add some option to enable / disable, so that prone, unconcious or 0 hp creatures do not count for cover purposes.

I haven't seen any official rule or answer to the effect that such creatures don't count as cover for ranged attacks, but common sense rules above all things. In our group, creatures on the ground do NOT count as cover.

Imagine attacking a creature with a bow, and in front of it there is another unconscious creature ..... lying down, it doesn't make much sense to apply cover.

It would be nice if there was an option in this sense to enable / disable, for those who want more realism and common sense.

Well, it is a proposal ... I do not know if it could be contemplated or realized.... But it would be useful to activate some option that does not count as cover the prone, unconscious and 0 hp creatures (this last one is as if it were unconscious, but it would avoid to be marking the unconscious  condition of each creature that is at 0 hp).

**Comment by trioderegion** [comment]
Finer grain control over what provides cover when is definitely a reasonable request. The ongoing rework will make that a lot easier.

I dont think Helpers will *directly* tie into conditions, but tokens will now have an adjustable level of cover at the very least which can be modified by other processes.

We will definitely look into 0HP creatures providing no cover as well. 

Thank you for the suggestions 😄

**Comment by Fridan99** [comment]
Another option might be to insert some kind of button in the hud of the token.... to make it "disappear" from the calculation of the lines for the cover..... This would be a manual solution for unconscious or prone conditions, e.g. in case you can't link it to the conditions.

**Comment by kandashi** [comment]
Possibly a flag on the token, then that could be altered by active effects ....

**Comment by Fridan99** [comment]
Any plans to incorporate any of these ideas into milestone 3.0.0?

**Comment by trioderegion** [comment]
We wont be adding a button to the HUD of the token for such a specific effect, and I dont want to implement it globally since if a Huge creature is prone...it still likely provides cover for smaller creatures. I think this would be best done via interfacing with our flags/cover api. The details of which I do not have on hand, but should be possible.

0HP creatures would behave the same way in that they still may provide cover.

I am going to close this one for now and look into examples of modifying a placeable's cover via scripting.

**Comment by trioderegion** [comment]
`token.setCoverValue(Number)` with Number = [0,3] has been added to v3.
