### ISSUE TITLE
[Feature request] Allow for customizing the DC of the save required, or removal of the save alltogether 

### ISSUE THREAD

**Issue by Zarhog** [trioderegion/dnd5e-helpers#161]
for some reason when a creature takes a great wouund, if that creature is a player it prompts the player for a con save. this is not mentioned in the modual nor do I want the save, I just want the automated you took 1/2 HP from I swing so you loose something , can this be fixed or a toggle added.

![image](https://user-images.githubusercontent.com/76391362/128647303-c333b0ce-f1a0-4076-8f86-092135e78a66.png)

**Comment by kandashi** [comment]
This will go live in v3.0.0
