### ISSUE TITLE
Invisible Walls considered full cover

### ISSUE THREAD

**Issue by crymic** [trioderegion/dnd5e-helpers#162]
Invisible Walls give full cover bonus.. Was wondering why there was a -40 on a roll. Invisible walls should be ignored or at least offer an option to enable or disable it.

**Comment by trioderegion** [comment]
We will make sure this is taken into account in the Cover rework coming in 3.0.0.

**Comment by Fridan99** [comment]
That would complicate things. Invisible walls are supposed to be solid (window, force wall, etc...). They should give total cover... 

Here is Foundry's definition

Invisible Walls
These walls block token movement, but neither vision nor sound. Walls of this type are ideal for windows, or any transparent, but solid obstacle. They are colored cyan on the Walls layer.

They are designed to block movement, so it is logical that they provide full cover. Objects are not supposed to pass through these walls.

**Comment by trioderegion** [comment]
The upcoming v3 should include the ability to change the cover value on a per wall segment basis.

**Comment by trioderegion** [comment]
This is now the default behavior in v3. Invisible walls do not provide cover.
