### ISSUE TITLE
[Bug] Configuration window buttons appear behind the settings text

### ISSUE THREAD

**Issue by fiagewinnt** [trioderegion/dnd5e-helpers#164]
I'm on the current version of both Foundry and the macro and noticed that in the settings window under "Combat Helpers" the "Save Changes" and "Reset Defaults" buttons appear kind of behind the settings. They can still be operated though.

![image](https://user-images.githubusercontent.com/61601634/131247343-19b30fe8-df8e-4482-99b3-fc7b9e3af35c.png)

**Comment by trioderegion** [comment]
Does this occur when the module that adds those globe symbols is disabled? Also, what is that module?

**Comment by fiagewinnt** [comment]
Hi @trioderegion.
That's DF Settings Clarity - https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-settings-clarity
It shows which settings are world settings and which are client settings. 

After disabling it, the buttons show up at the end of the window again. I'd like to use the other module further on and since it's just a minor interface bug it's fine if fixing it is not really a priority for you. The buttons still work even though DF Settings Clarity interferes with it. 

![image](https://user-images.githubusercontent.com/61601634/131314288-d7a812d3-a1cd-448c-85bf-57fcd1e292e3.png)

**Comment by trioderegion** [comment]
I really have no idea why it would be doing that. We are just using a standard Form Application. Have you checked with the Author of Setting's Clarity? Feel free to ping me in that issue.

Not trying to shirk responsibility, just confused as to why this would happen.

**Comment by fiagewinnt** [comment]
After updating to your newest version today the issue has resolved itself. 🥳 Still thanks for the replies.

![image](https://user-images.githubusercontent.com/61601634/131340984-9fb5dfa6-63c9-433f-8ed0-3755495c2e24.png)

**Comment by trioderegion** [comment]
I'm not going to look a gift horse in the mouth, haha. Good to hear!
