### ISSUE TITLE
[Bug] - Great Wound saving throw requested even if Great Wound is disabled.

### ISSUE THREAD

**Issue by RavenknightDM** [trioderegion/dnd5e-helpers#165]
Hiya, thanks for the mod!
Currently (3.0) the mod asks for a saving throw for any creature reduced to 0 hp even if the Great Wound feature is disabled.

**Comment by kandashi** [comment]
Whoops, lemme check on that

**Comment by Avitale34** [comment]
Came here for same reason :)

**Comment by trioderegion** [comment]
Corrected in 3.0.1

**Comment by Avitale34** [comment]
Is this change live?

**Comment by trioderegion** [comment]
it is not. trying to batch up the loose ends of v3.0.0. Will be released in 4-6 hours.
