### ISSUE TITLE
Combat Action Manager not updating automatically

### ISSUE THREAD

**Issue by RavenknightDM** [trioderegion/dnd5e-helpers#166]
Hiya, I'm unsure if this is the intended behavior or not with 3.0.0, but I've noticed that the Combat Action Manager doesn't update automatically anymore on use of an action, reaction etc. You can still tick the stuff off manually and get the desired conditions so it's not a big thing. But the automatic reaction ticker was a great thing for a forgetful DM such as myself. :)

**Comment by kandashi** [comment]
Can you provide more information on what exactly is not working.
What modules are you using for rolling, what items, Token Action Hud or not etc...

**Comment by trioderegion** [comment]
If we can get more details, I can roll this into 3.0.1

**Comment by RavenknightDM** [comment]
Hi guys, sorry for the late reply (had a rough day at work), I myself use Midi so my guess would be that its a conflict with one of my many other mods. I will try and disable some of the likely suspects and get back to you.

**Comment by RavenknightDM** [comment]
It seems that the conflict is with the "Chat Portrait" module. Sorry for not testing this out before posting in the first place. :)

**Comment by trioderegion** [comment]
It appears that Chat Portrait messages do not include the `speaker.token` field, which we require to determine which token initiated the action.

I'm trying to resolve this, but it may not make it into 3.0.1.

**Comment by trioderegion** [comment]
Chat Portrait 0.5.9 addresses this issue!
