### ISSUE TITLE
Open Wound Table will not be rolled after Critical Hit occur

### ISSUE THREAD

**Issue by ShockoVideo** [trioderegion/dnd5e-helpers#167]

**Comment by trioderegion** [comment]
Any further details? reproduction steps? setup?

**Comment by ShockoVideo** [comment]
![](https://media.discordapp.net/attachments/722566083499786352/881877631820247060/unknown.png)

**Comment by trioderegion** [comment]
Reproduction steps, please?

**Comment by ShockoVideo** [comment]
I setup in Helpers settings Open Wound Table name, and Open Wound on critical hits. But when in combat critical hit occurs, there are no Open Wound Table roll

**Comment by trioderegion** [comment]
I believe this is fixed in 3.0.1
