### ISSUE TITLE
[Incompatibility] 5eHelpers might have conflicts with Long-Rest-Hit-Dice-Healing

### ISSUE THREAD

**Issue by tagnullde** [trioderegion/dnd5e-helpers#169]
I opened an issue on the LRHDH github too. Not sure who needs to be the active part in this.

https://github.com/schultzcole/FVTT-Long-Rest-HD-Healing-5e/issues/15

**Comment by trioderegion** [comment]
Is there broken functionality?

**Comment by trioderegion** [comment]
Mirroring linked issue and closing
