### ISSUE TITLE
The question of the great and open wounds

### ISSUE THREAD

**Issue by MarsKening** [trioderegion/dnd5e-helpers#170]
Good time of day. I didn't quite understand how the wounds should work and how to set up the tables correctly. What and how should I configure to make a roll on the table? According to which table? Where is she? Or is it just an alert for further narrative determination of the type of wounds? And I also did not understand why there is not at least some indication that the wound was received? Although in the settings I set it to have an effect on the character.

ps: yes, I don't really understand English, so I might have misunderstood something. Can I have an explanation from the guide " for stupid barbarians?" Program version 0.8.9

**Comment by kandashi** [comment]
Setup the table however you like. I personally use the table from the DMG. 
Setup the table name setting in the module settings to the name of the table within foundry
If the table has items (or items with active effects) those can be auto added onto the actor when the table is rolled

**Comment by MarsKening** [comment]
> Настройте стол так, как вам нравится. Лично пользуюсь таблицей от DMG.
> Задайте для параметра имени таблицы в настройках модуля имя таблицы в литейном цехе.
> Если в таблице есть элементы (или элементы с активными эффектами), они могут быть автоматически добавлены к действующему субъекту, когда таблица катится.

Damn, I didn't think about that somehow. It really turned out to be a question of a "stupid barbarian". Thank you so much for the answer! And thank you for your work.
