### ISSUE TITLE
[Feature Request] Add support for the sharpshooter feat

### ISSUE THREAD

**Issue by Jedstonk** [trioderegion/dnd5e-helpers#171]
Would it be possible to add support for the Sharpshooter feat so that it ignores 1/2 and 3/4 cover for ranged attacks? I have a player in my game that has this feat, which makes the automatic mode inaccurate.

**Comment by trioderegion** [comment]
This is already included in Helpers 😃 . Check your special traits, about halfway down there is a checkbox for ignoring cover. As seen below.

![As seen here](https://github.com/trioderegion/dnd5e-helpers/raw/master/.github/helpers_special_traits.webp)
