### ISSUE TITLE
Id not defined for owned tokens when owner is not connected

### ISSUE THREAD

**Issue by thatlonelybugbear** [trioderegion/dnd5e-helpers#172]
![image](https://user-images.githubusercontent.com/7237090/131856322-aabface0-6a0e-457e-a647-7b76e240fce0.png)

 DnD5eHelpers v3.0.1, 5e 1.4.2, Foundry 0.8.9 (hosted on the Forge)
 Disclaimer: I just started using the Forge, so there might be a chance of something not configured right, but I checked what I could.
 
This error triggers when only a GM account has joined and in an active combat, the turn of a token that is already associated with a user (who is not connected in this case) comes up.

The GM is not the owner of the specific token and thus the 'id' is not defined.

This will keep happening if a player is not connected for a session and the DM has to control the actor.

This probably is the reason why, no actions are automatically recognized during my testing of the v3 update.

**Comment by thatlonelybugbear** [comment]
Update: Does not seem that I can repro this anymore. Trying to figure out what did I change in the meantime.
Maybe it had to do with some user permissions on the Forge.

Don't know whether I should close this issue tentatively for now and see if I can repro in the future/find out what was the issue in the first place, or leave it open.

**Comment by trioderegion** [comment]
It is certainly odd. For now, we will close this issue. If it ever pops back up, simply create a new one. I will still look into what can be done on our side to potentially eliminate this issue of First Owner.
