### ISSUE TITLE
Uncaught TypeError: can't access property "scale", this.icon is undefined

### ISSUE THREAD

**Issue by Novynn** [trioderegion/dnd5e-helpers#176]
I've tracked down an annoying bug to this module. I couldn't figure out why this was happening but it is reproducible in a blank world with just dnd5e helpers loaded with it's default configuration.

Foundry version: 0.8.9
DND5e version: 1.4.2
DND5e Helpers version: 3.0.1
Browser: Firefox 92

Reproduction steps:

1. Place token
2. Add token to combat
3. Delete token
4. Run `game.canvas.tokens.activate();` in the browser console (calls refresh on tokens)
5. The token still exists in some capacity but in a broken state: `Uncaught TypeError: can't access property "scale", this.icon is undefined`
6. This breaks future token placement etc

**Comment by trioderegion** [comment]
weird, but confirmed
