### ISSUE TITLE
Missing Action Management HUD button

### ISSUE THREAD

**Issue by franckflo** [trioderegion/dnd5e-helpers#181]
Thanks for this great module! I use the Action Management options in your module and noticed that recently the "Additional control added to the token HUD during combat to manually adjust actions." is not visible anymore on any of the tokens. The Action Management overlay is working, but I can't find the extra button to manually adjust it for tokens. I looked into the module settings and didn't find any unchecked option about it. Thanks for looking into it!

**Comment by trioderegion** [comment]
Ah, yea, the dialog with checkboxes was removed in favor of simply clicking on the icon in the displayed hud 😄 
![image](https://user-images.githubusercontent.com/14878515/133131062-26f26092-6ae4-40a1-899d-51176bf2b46d.png)

**Comment by franckflo** [comment]
Oops, I missed that change, which is awesome. Sorry about that!
