### ISSUE TITLE
[TypeError] Cannot read properties of undefined

### ISSUE THREAD

**Issue by tagnullde** [trioderegion/dnd5e-helpers#183]
When opening the prototype token this pops in the console. At one point it spammed hundreds of errors (others - no screenshot sadly) in to console and foundry almost locked itself up.

![Screenshot at 2021-09-14 21-10-34](https://user-images.githubusercontent.com/44159008/133320182-b01319c0-4f21-4428-8c8b-00c643fec194.png)

**Comment by trioderegion** [comment]
oof, that's rough, but I have an idea as to the cause. Sorry for the troubles -- this, among a couple other fixes will be coming shortly.

**Comment by tagnullde** [comment]
No worries. You do this in your spare time and for the greater good. So thank you in the first place. :)
And thank you for looking into it.
