### ISSUE TITLE
[Uncaught in Promise] Invalid Basetexture

### ISSUE THREAD

**Issue by tagnullde** [trioderegion/dnd5e-helpers#184]
I was playing with the cover calculation and once finished I removed the player token from the canvas, moved monster tokens back to their rooms and then reset fog of war. Everytime I open the scene now I get these errors:

![grafik](https://user-images.githubusercontent.com/44159008/133421332-e7120dd4-0747-469b-a51a-2f116faa276c.png)

![grafik](https://user-images.githubusercontent.com/44159008/133420538-713ff0d3-d263-4e22-9362-2a606abb7906.png)

Oh an I just noticed that one of the monster tokens isn't accessible anymore. Looks like part of the backdrop.
I can't even select it. o.O

Disabling 5ehelper didn't resolve the issue either. It still tries to load that image.

**Comment by tagnullde** [comment]
Ok - I was able to open the scene in another browser (Firefox was broken, Chrome worked). The token has this cover status indicator:

![grafik](https://user-images.githubusercontent.com/44159008/133424580-34597215-096a-4ab1-9c13-29c4b59c5695.png)

**Comment by trioderegion** [comment]
I believe this is addressed by #176 . Please re-open if you still experience issues related to this.
