### ISSUE TITLE
libWrapper: Potential conflict detected between DnD5e Helpers and Long Rest Hit Die Healing for D&D5e.

### ISSUE THREAD

**Issue by Tatonker** [trioderegion/dnd5e-helpers#186]
Hi all,

I'm getting the following error message 

```
libWrapper: Potential conflict detected between module DnD5e Helpers and module Long Rest Hit Die Healing for D&amp;D5e.
Detected non-libWrapper wrapping of 'CONFIG.Actor.entityClass.prototype.longRest' by module dnd5e-helpers. This will potentially lead to conflicts.
```

I don't anything actually breaks, just wanted to flag it.

Tatonker

**Comment by SR5060** [comment]
This also happens with the short rest recovery module. it appears that it may block some of the features of that module (e.g. detection of song of rest)

**Comment by trioderegion** [comment]
You say "may block". 

Have you run into any actual issues, apart from this warning?
