### ISSUE TITLE
libWrapper: Potential conflict detected between DnD5e Helpers and module short rest recovery for D&D5e.

### ISSUE THREAD

**Issue by SR5060** [trioderegion/dnd5e-helpers#192]
![image](https://user-images.githubusercontent.com/85184490/134694814-a0ec22b8-e7c0-48df-9c96-b439fab07ece.png)

appears to block some of the features (detection of song of rest) for that module)

**Comment by trioderegion** [comment]
This is simply a warning -- does it actually interfere with anything?

**Comment by SR5060** [comment]
My players were mentioning that song of rest was not working, but initial testing looks to be functioning correctly. we can close and I'll do more testing
