### ISSUE TITLE
Suggestion: Add option to spells to lock to grid intersections

### ISSUE THREAD

**Issue by SR5060** [trioderegion/dnd5e-helpers#203]
I noticed that you were discussing a way to force spells to be placed on the grid lines (vs between gridlines) on discord. It would be super hands if there was a tool to force this globally for certain spell templates.

As far as I'm aware, no module supports that currently

**Comment by trioderegion** [comment]
Due to the varied usage of templates, I am going to have to reject this feature request, upon further consideration. Thank you for taking the time to suggest it.
