### ISSUE TITLE
Possible error with Undead Fortitude. 

### ISSUE THREAD

**Issue by Fridan99** [trioderegion/dnd5e-helpers#205]
I think the dnd5e helpers has some kind of bug with the undead fortitude. I have noticed that when deducting damage to creatures with undead fortitude, most of the time they still survive, I have done tests with high damage, and it seems that some kind of conflict occurs. In this test I have deducted 80hp to the zombie, and put as normal damage, the DC should be 85.... but the zombie is still standing. 

![1](https://user-images.githubusercontent.com/86131373/138783726-ddc93ba6-28e6-4a96-9fbf-c871c37ad4fd.jpg)

![2](https://user-images.githubusercontent.com/86131373/138783728-99f8fe7a-9032-4ebb-a517-abb53322a16f.jpg)

another test deducting 20hp, with a roll of 7... it should be dead... and it's still standing... xD

![3](https://user-images.githubusercontent.com/86131373/138784147-039f161b-1f39-4ad4-9ec3-3ae0f5d7a800.jpg)

I use betterrolls as well I don't know if it interferes

the possible error was noticed by the players and myself (GM) during a game yesterday, Sunday. A zombie managed to survive more than 10 attacks, and in fact we finished the game and the zombie was still alive xD. I checked the rolls, and it should have died several rolls back.

**Comment by MarkeyMarke** [comment]
@Fridan99 not sure how else to reach out to you; could you let me know what versions you're using for your environment? I have a similar issue but it doesn't work with advance saves:

**Environment**
- Foundry v0.8.9
- DND5e v1.5.3
- Hosted via The Forge
- BR5e v1.6.16
- DND5e Helpers 3.0.3

**Comment by Fridan99** [comment]
> @Fridan99 not sure how else to reach out to you; could you let me know what versions you're using for your environment? I have a similar issue but it doesn't work with advance saves:

Foundry 0.8.9
Dnd5e System 1.5.3
Auto-hosted
Better Rolls 1.6.16
Dnd5e Helpers 3.0.3
Combat Utility Belt 1.7.1
Midi-Qol 0.8.82
![1](https://user-images.githubusercontent.com/86131373/141333495-96c44892-74a7-47b0-b9c2-7e501aa9a9a7.jpg)

If you have problems I can tell you the configuration I have in each module. But for me it works perfec
