### ISSUE TITLE
[Feature Request] PC/NPC with Magic Resistance prompt "Is save from magic? yes/no" on using a saving throw.

### ISSUE THREAD

**Issue by SearingRains** [trioderegion/dnd5e-helpers#207]
I apologize if it is a faux pas to request a feature, but I figured I might not be the only one that could use this, and things you have set up already seem like this would be relatively simple to implement.

So basically, I was reaching out to see if there was a way to prompt him/someone/NPC with the Magic Resistance trait when he makes a saving throw in foundry to ask "Is this a save from a magical effect?; yes/no" as a way for us to never miss his (or monsters like fiends!) advantage from the Magic Resistance trait.

We're 14 levels and 2 years in, and this player with the Magic Resistance trait is really good at staying focused and remembering his spells and abilities. We just had a Beholder fight though, and both of us forgot about the trait for almost the entirety of the fight, because we were both tracking so many things.

And also I want to thank you... My Beholder became an undead Beholder with Undead Fortitude... and the prompt at the end of a 4.5 hour fight to roll for his Undead Fortitude trait was extremely awesome, as I had definitely forgotten. So it seems like you already have things in place to handle a request like this Magic Resistance trait!

Thanks for all of your hard work on this module - It has been instrumental in a several fights in making things like legendary and lair actions and undead fortitude run smoothly!

**Comment by kandashi** [comment]
No issue with logging a request. However this would be a detraction from the original 5e helpers "rule" of not changing any core code, only adding on. A feature like this would require a slight deveation, but may be considered in the future

**Comment by trioderegion** [comment]
Considering this further, I'm going to have to say that this is outside the scope of Helpers. Midi-qol of LMRTFY may be better candidates for this kind of functionality.
