### ISSUE TITLE
[Incompatibility] Automatic Undead Fortitude checks are incompatible with 'Better Rolls for 5e'

### ISSUE THREAD

**Issue by MarkeyMarke** [trioderegion/dnd5e-helpers#208]
### Issue
It seems that the Undead Fortitude check relies on the base rolling system for dnd5e. This seems to break when paired with Better Rolls for 5e (BR5e); as it seems to override the base rolling behavior.

### For context
![image](https://user-images.githubusercontent.com/32396474/140162913-47f5226f-de02-44a2-8ec1-913ff4bb5e9c.png)

The image above shows two types of rolls produced by BR5e; a single roll which could be given advantage/disadvantage and dual rolls which rolls two dice simultaneously and lets the player interpret if there was advantage/disadvantage. It seems this replaces the base roll made by dnd5e entirely.

### Proposal
It seems that Undead Fortitude Checks currently has three modes:
- No checks
- Quick saves
- Advanced saves

Is it possible to add a 4th mode '**Show DC**' (could probably name it better) which behaves in the following way?

1. GM subtracts HP
2. Module prompts GM if the damage was Radiant/Critical Hit, or just a normal hit
3. GM inputs the damage as a normal hit
4. Module rolls for Consitution Saving Throw (and does not check if it passes or not)
5. Module calculates DC and outputs a chat message "Undead Fortitude DC: X"
6. GM checks the roll and DC manually and determines if the Zombie is dead or alive

**Comment by kandashi** [comment]
Does the BR system work with the advanced saves at all ?

**Comment by MarkeyMarke** [comment]
> Does the BR system work with the advanced saves at all ?

https://user-images.githubusercontent.com/32396474/140669116-a5012662-e2ed-4e46-90f1-b2b91c338402.mp4

It does not seem to work with advanced saves either.

**Comment by MarkeyMarke** [comment]
I see that there was another user experiencing a similar issue and fixed it using advanced saves: https://github.com/trioderegion/dnd5e-helpers/issues/205#issuecomment-951873555

I think my case is slightly different since it's throwing an undefined value, rather than any number at all. It might be due to a different environment?

**Environment**
- Foundry v0.8.9
- DND5e v1.5.3
- Hosted via The Forge

**Comment by MarkeyMarke** [comment]
Looking at it further, it does seem that BR5e overrides the output of `await actor.rollAbilitySave(...)`. I get this when I run the console command:
![image](https://user-images.githubusercontent.com/32396474/141222148-ce4dac8d-ec96-4e54-9088-c438c5a5b595.png)

Since BR5e allows for Dual Rolls (roll twice without saying there's advantage or disadvantage), it's too difficult to detect if the Zombie passed the roll or not. It would make more sense to send users a DC and let them manually decide after a CON save.

**Comment by trioderegion** [comment]
We will look into this for 3.0.4. Better Rolls is quite the outlier as far as rollers are concerned.
