### ISSUE TITLE
Suggestion: Exception with tokens that collision with wall lines.

### ISSUE THREAD

**Issue by Fridan99** [trioderegion/dnd5e-helpers#213]
Problem with wall lines that cannot be assembled with squares. It seems to be a very common problem in my games. The module works perfectly, but there are circumstances, and apparently they are more common than they seem, that it is difficult to find a perfect alignment of the walls with the maps and squares, in many cases some rooms or parts of the map can not be squared with the squares. 

My idea, is the following (for the record, I don't know if there can be any possibility). 

In case some token touches a wall partially, only the direct line between the attacker and the token will be taken into account. I don't know if it is possible to make some kind of exception, in case the token touches "line walls", eliminating from the cover calculation the collision lines with the walls and token. 

In this particular map, I tried to limit the walls to the square lines, but in other rooms they did not fit the map walls. It is difficult to maintain harmony between maps and squares throughout all the scene. 

![1](https://user-images.githubusercontent.com/86131373/141028562-ea44786d-2c0c-4932-ac73-258298687876.jpg)

I already reported this "error", which is not an error per se previously in this thread. Well, it is a suggestion in case it is feasible that the calculation takes exceptions in case of collision with walls and calculation line. I already reported this "error", which is not an error per se previously in this thread. Well, it is a suggestion in case it is feasible that the calculation takes exceptions in case of collision with walls and calculation line. 
https://github.com/trioderegion/dnd5e-helpers/issues/206

**Comment by trioderegion** [comment]
Unfortunately, it is not really feasible to start interpreting user intention as far as cover is concerned. If a token clips into a wall, the  token is going to have cover.

Aligning walls to the foundry grid is extremely important for the cover calculator in dense areas.
