### ISSUE TITLE
[Suggestion] Limit legendary actions prompt for when the actor actually had legendary actions left

### ISSUE THREAD

**Issue by FGiorgi** [trioderegion/dnd5e-helpers#214]
As of now, if you have the legendary actions prompt active, it prompts every turn, even if the actor has already spent all of their legendary actions. It´s a bit confusing and kind of annoying when you have big fights with a lot of combatants.
If possible it would be great if it could check if the actor has legendary actions left and, if it doesn´t, stop prompting until they recharge

**Comment by trioderegion** [comment]
This makes total sense. Thank you for pointing this out.
