### ISSUE TITLE
[Bug] Cannot create chatmessages in macros with dnd5e helpers enabled

### ISSUE THREAD

**Issue by Krigsmaskine** [trioderegion/dnd5e-helpers#216]
Version 3.0.3. I was trying to help someone out with macro-ing some lingering injuries reminders, and suddenly ran into some weird errors from ActionManagement.js at the _preCreateChatMessage hook. Just so you don't have to dig through the code of the macro, it rolls from a table, gets a result and creates an ActiveEffect with the result as a flag, then outputs the result as well in a ChatMessage. The latter fails with DnD5e helpers enabled, succeeds when disabled.

I've attached the macro here.
[shouldhavebeenajson.txt](https://github.com/trioderegion/dnd5e-helpers/files/7541953/shouldhavebeenajson.txt)
i.

Error here, the syntax is the table roll result in text.
![image](https://user-images.githubusercontent.com/39592771/141861015-c55094ab-1074-435a-971a-3cea138e5f4f.png)

**Comment by trioderegion** [comment]
oof, that's no good. Sorry for the issues. I'll try to get a fix by this weekend.

**Comment by trioderegion** [comment]
This may have been implicitly fixed by the work done for #212. If this issue persists in 3.0.4, please reopen this issue.
