### ISSUE TITLE
"No Regen" effect disables regeneration even when inactive

### ISSUE THREAD

**Issue by jflevesque** [trioderegion/dnd5e-helpers#217]
Hi,

I just noticed that if you disable the No Regen active effect on a token (but don't delete it), it is still taken into account to prevent regeneration. During a fight with vampires for example, it would be much easier to simply toggle the effect, since it could come back the next round based on player actions.

Based on this, I would suggest to check if the effect is active (passive or temporary) for it to prevent the regeneration, but ignore the presence of the effect it if its set to Inactive.

**Comment by trioderegion** [comment]
This is indeed an oversight. Thanks for bringing it to our attention.
