### ISSUE TITLE
Suggestion: Message (alert) in track actions

### ISSUE THREAD

**Issue by Fridan99** [trioderegion/dnd5e-helpers#225]
Combat Helpers
Display Used Actions as Status Effect

Assemble a warning message in the chat or screen, when you try to use a bonus action or reaction feature, and you have already used it up (so you currently have 0).  

Action tracking should be used to alert rather than remember what actions have been used. It is easy to remember on your turn what actions you have performed, where the player's control can slip is whether a feature was a bonus, reaction or no action..... and that is where the conflict really lies. With a reminder the players are alerted that they can NOT use such a feature because they have no X action (bonus, reaction.....etc) left. 

Therefore my suggestion is that when the track action has been consumed (action, bonus action, reaction), if you try to execute any feature with this consumed action, a warning message is displayed, warning that it has already been consumed, and if you really want to use it. 

Really the problems are the bonus action and reaction. Having some option to choose which actions to track would be positive, and to be able to avoid tracking actions, since with multiattack, extra attack would be a tedious continuous message.  

A simple suggestion.

**Comment by Fridan99** [comment]
something similar to midi-qol's concentration, which warns you if you want to cast a concentration spell if you already have one active. 
![1](https://user-images.githubusercontent.com/86131373/144754308-f9b18760-d8db-47e6-8f03-8ab890b9379a.jpg)

In this case it would be for example if you want to perform a feature bonus action, reaction..., when you currently have 0 available. As an example of warning text of a bonus action, **You have already used your bonus action, are you sure you want to use this ability?**

I think it would be more efficient as a reminder than as a post in the round. Slips are generally not due to not remembering what action you have taken in your turn, but due to not remembering what action was a feature, skill, etc...

**Comment by trioderegion** [comment]
This would require hooking into the item rolling methods directly, rather than inspecting the final result in the chat log, which is the current approach.

I'm not sure how I feel about this, particularly as a GM that often moves multiple baddies as a group on the same initiative (then cleans up any reactions it detected because of that).

I could definitely see a Helpers expansion module getting more into the guts of the item rolling system for this.

I'll let the other devs weigh in on this as well.

**Comment by trioderegion** [comment]
We discussed this idea and are in agreement that this operation would be more invasive that Helpers wants to be as it would require wrapping the `Item#roll` method, which is a can of worms.

However, @Kekilla0 was kind enough to provide a sample snippet (untested, but right idea) for how you would implement this functionality in a expansion module.

```javascript
const original = getDocumentClass("Item").prototype.roll //double check this part
game.dnd5e.entities.Item.roll = function(){
  const token = this.actor.token ?? this.actor.getActiveTokens()[0];
  if(!token /* || action traking isn't on */) return original();

  const actions = token.getActionFlag();
  if(!actions || actions[this.data.data.activation.type] == 0) return original();

  /* Display dialog */
}
```

We all appreciate your support and enthusiasm for the module 😊

**Comment by Fridan99** [comment]
Great, I think it can be very useful to implement it in an expansion module. Thanks to you and @Kekilla0 dedication and knowledge, with a reminder I certainly think it would be more useful to track actions. Probably some option to decide to discard actions (the easiest to track and the ones that would present more tedious reminder problems by the use of extra attack, multiattack....).

**Comment by Fridan99** [comment]
> We discussed this idea and are in agreement that this operation would be more invasive than Helpers wants to be as it would require wrapping the `Item#roll` method, which is a can of worms.
> 
> However, @Kekilla0 was kind enough to provide a sample snippet (untested, but right idea) for how you would implement this functionality in a expansion module.
> 
> ```js
> const original = getDocumentClass("Item").prototype.roll //double check this part
> game.dnd5e.entities.Item.roll = function(){
>   const token = this.actor.token ?? this.actor.getActiveTokens()[0];
>   if(!token /* || action traking isn't on */) return original();
> 
>   const actions = token.getActionFlag();
>   if(!actions || actions[this.data.data.activation.type] == 0) return original();
> 
>   /* Display dialog */
> }
> ```
> 
> We all appreciate your support and enthusiasm for the module 😊

I will try your snipped untested for the reminder track action. One question, could it be that in the 6th line instead of == it is ===?
