### ISSUE TITLE
[Feature Request] Action Management hud visible settings for individual users

### ISSUE THREAD

**Issue by Krigsmaskine** [trioderegion/dnd5e-helpers#226]
Hi,

I really enjoy the overview of the action management hud, but some of my players don't agree. If a feature could be implemented to either only show the GM or even better, by user-basis, that'd be appreciated.

**Comment by Kekilla0** [comment]
Update line 50 of ActionManagement.js's scope to "client".

**Comment by Kekilla0** [comment]
Update will be in next version, might be a while.
