### ISSUE TITLE
in v9 Walls not change cover

### ISSUE THREAD

**Issue by rinnocenti** [trioderegion/dnd5e-helpers#238]
edit wall (green or blue walls) not change ther covers.
when I edit a covering for a wall, it reverts to its original status.

**Comment by trioderegion** [comment]
What wall settings are being used for your walls, just so I'm looking at the right thing.

**Comment by trioderegion** [comment]
I think I see what is going on. Sight Restriction must be "Normal" for the cover settings to apply. I know we did this purposefully, but we should revisit this restriction for v9 and the new restriction settings for walls.

**Comment by GhostwheelX** [comment]
I think I'm having the same issue when using Terrain walls, even when the terrain walls are doubled meaning that they entirely block line of sight to the target.

**Comment by trioderegion** [comment]
Apologies for this resolution to take so long, its time for another round of patches.

Just as a heads up, I can't promise that we will be able to support limited vision walls, but I'll do my best.
