### ISSUE TITLE
Translation doesn't seem to activate

### ISSUE THREAD

**Issue by remiverdel** [trioderegion/dnd5e-helpers#239]
Hi,

I just saw that you had a French translation in the lang folder however, even if I'm using a French version of Foundry and of Dnd, the French translation doesn't seem to kick in for the module. It stay sin English in the settings and in all the prompts.

Thanks !

Rémi

**Comment by trioderegion** [comment]
Hmm, that is certainly odd. I'll look into it as soon as I get the chance (might be a few days).

**Comment by ddealmei** [comment]
The pull request should fix it, there were some JSON formatting issues causing errors during the parsing of the file.

**Comment by trioderegion** [comment]
Thank you so much for the PR. I am back on Helpers development, so I'll get this rolled in soon as I can!
