### ISSUE TITLE
Suggestion: implement in special traits ignore half cover

### ISSUE THREAD

**Issue by Fridan99** [trioderegion/dnd5e-helpers#240]
I have seen that in the special traits section of the character sheet, there is an option in the Feats field to ignore the 1/2 and 3/4 cover..... but there is no option for only 1/2.

The thing is that there are certain skills or items, such as the item Wand of war mage (pg 212 DMG) that only ignore 1/2 cover from spell attacks.

It would be interesting to implement the extra option to choose only ignore 1/2 for this kind of special cases.
![1](https://user-images.githubusercontent.com/86131373/147960097-6f17ae43-e776-4d40-b4d3-d938107ec958.jpg)

I don't know if there is any other way to handle this automatically.... xD

I don't know if it is useful, or if it can be done.... the truth is that there are multiple situational occasions.

**Comment by GamerFlix** [comment]
Option for this has been coded and awaits addition as per https://github.com/trioderegion/dnd5e-helpers/pull/259

**Comment by trioderegion** [comment]
And merged.
