### ISSUE TITLE
Legendary Actions not Incrementing on Use

### ISSUE THREAD

**Issue by fel0pez** [trioderegion/dnd5e-helpers#241]
DND5e Helpers Version: 4.0.0.0
Foundry Version: 9.0.0.9
DND5e Version: 1.5.6

When using Legendary Actions, I get the prompt, but it does not Increment Uses in the NPC Sheet when I click to Use a Legendary Action or Resistance.

![prompt](https://user-images.githubusercontent.com/49355410/148148512-d76f9677-cd78-4269-b126-c0c94661e6e3.PNG)

![sheet](https://user-images.githubusercontent.com/49355410/148148540-ec7f7fb7-7de5-4733-94cf-4cd7fba8e298.PNG)

It seems like the module keeps track of Legendary Resistances separately of the sheet, if it's not possible for it to modify the sheet directly, can it also keep track of actions in the same way?

**Comment by trioderegion** [comment]
Make sure that the features are consuming the "legact" Resource in the item's details.

**Comment by fel0pez** [comment]
What do you mean by that?  This isn't an item I'm having issues with, it's any NPC with legendary actions.

**Comment by trioderegion** [comment]
Features, such as legendary actions, are referred to as "Items" in foundry. Sorry for the confusion.  Helpers does not automate the consumption of legendary action counts -- the system will do that naturally IF the feature is set up to consume the legendary action resource as show below. Note The Activation Cost field is what Helpers reads to identify a legendary action.

![image](https://user-images.githubusercontent.com/14878515/148229090-67999799-cad6-49c8-97ef-b05f3caace5f.png)

**Comment by fel0pez** [comment]
That did it, thank you.  Foundry's documentation is inscrutable.  You've been really helpful even though it wasn't directly a problem with helpers. :)

**Comment by trioderegion** [comment]
Glad its working now!

And just to close the loop -- legendary resistances have a similar attribute field "legres".
