### ISSUE TITLE
Volatile Wild Magic Surge problem

### ISSUE THREAD

**Issue by rockwallguy** [trioderegion/dnd5e-helpers#249]
Volatile magic surge, in the description, is supposed to roll a d20 and compare that value to 1+spell level+1d4 (when tides is expended).  

The display I'm getting is that the d4 is getting added to the d20, making surges _less_ likely rather than more likely. 

![image](https://user-images.githubusercontent.com/79724010/152743878-f52622d9-8152-43ee-ab62-21d1f6303bd6.png)

Edit: I messed around with it some more and eventually got a roll of -1, which indicates to me that it's actually comparing the d20-1d4, which makes sense.  But the little tooltip that pops up is wrong.  FYI.

**Comment by trioderegion** [comment]
That tooltip for the volatile surge has been haunting me since it was first added, haha. For "reasons", its...surprisingly difficult to show the numbers we want to show in that tooltip.

That said, I'll do another pass - thanks for the heads up!
