### ISSUE TITLE
Reaction Not Applying (CUB, MIDIQol)

### ISSUE THREAD

**Issue by Tetraplasm** [trioderegion/dnd5e-helpers#25]
![Screen Shot 2020-11-21 at 8 49 11 PM](https://user-images.githubusercontent.com/73313551/99894678-0eec6c80-2c3b-11eb-9613-c09c23fdbede.png)
Hello,

I'm not certain what interaction between modules I've got that is causing this problem. I have a custom status named "Reacted" and have properly entered that name per the instructions, but I noticed in other people's submissions that there have been problems with how CUB renames its statuses on the back end. 

Please let me know if you need further information.

**Comment by kandashi** [comment]
What type of chat cards are you using for midi?

This is failing to recognise what type of action is being used, not what condition to use for the effect.

**Comment by Tetraplasm** [comment]
![Screen Shot 2020-11-22 at 12 44 35 PM](https://user-images.githubusercontent.com/73313551/99916715-9203d600-2cc0-11eb-8fad-f79a6cdc2b0a.png)
I believe this is the section you're referring to. Let me know!

**Comment by Tetraplasm** [comment]
After updating all my modules between the time of my previous posting and now, without changing anything, the reaction condition is being properly added and removed.

**Comment by trioderegion** [comment]
Would be interested to know the source, but I did add a few more failsafes for "weird" tokens. I'll claim credit regardless! 😆 

Happy gaming 😄
