### ISSUE TITLE
[Bug] Can't open helper settings window.

### ISSUE THREAD

**Issue by Arcainne** [trioderegion/dnd5e-helpers#251]
I'm unable to open the settings window for this module. Every time I click on the `Open Helpers Settings` button, it doesn't open and I get the following error in the console.
![image](https://user-images.githubusercontent.com/4230871/154637298-9db45b33-0b9f-416c-86a5-2316f9043f09.png)

I'm using 
 - DnD5e Helpers v4.0.0
 - DnD5e System v1.5.7
 - Foundry v9.249
 - Along with 105 other active modules...

**Comment by trioderegion** [comment]
Very strange, it seems like the bug is getting tracked down, so I'll close this issue. Do not hesitate to re-open if it is found that Helpers is doing something unexpected ❤️ . Thanks for the initial report.
