### ISSUE TITLE
Cover computation does not apply selected cover from walls / tokens

### ISSUE THREAD

**Issue by Kurokasa** [trioderegion/dnd5e-helpers#269]
Foundry VTT version 9
DnD 5e version 1.5.7
Dnd5e Helpers version 4.0.0

The cover application doesnt take the token or wall "Provides Cover" settings into account. No matter what is selected there it always applies half-cover. I dont see any errors and already tested it in a fresh world without other modules.
I use there Settings (cant find anything here that seems to do something about the problem):
Edit: Maybe this is a feature that my limited english just didnt get :D when i set the "Cover computation mode" in the settings to "Center Point Vision (Foundry Vision)" ist uses the "Provides Cover" settings from the token. Only thing i noticed is that walls wont save the "Provides Cover" settings if they are not visible, would be nice if it was possible but even i can think of reasons why it wont work.

![Screenshot 2022-03-26 112039](https://user-images.githubusercontent.com/102412559/160235210-b5532002-22ad-498c-9191-4753dedca397.jpg)

And this is the token setting iam talking about:

![Screenshot 2022-03-26 112115](https://user-images.githubusercontent.com/102412559/160235255-40afd22a-b257-4b06-b891-73c09f539661.jpg)

Thx for the gr8 work, the module is just amazing :)

**Comment by trioderegion** [comment]
I'll make sure this is addressed for the 4.1 release. I have already done a pass on the wall cover settings, which had plenty of bugs 😅 .

If you are bold, you could try the latest beta (pre-release) via the manifest install directly, but an update should be ready in a few days.

**Comment by trioderegion** [comment]
Yes, it appear that this has been fixed and will be included in the next release.
