### ISSUE TITLE
Unlocalized cover calculation helper setting

### ISSUE THREAD

**Issue by GamerFlix** [trioderegion/dnd5e-helpers#272]
![grafik](https://user-images.githubusercontent.com/62909799/160288488-b56ee451-107c-4086-89c6-4fb8348055d1.png)

**Comment by trioderegion** [comment]
It is used, just not localized since it wasnt exposed previous to this version.

**Comment by GamerFlix** [comment]
I was under the impression cover calculation blocking via drawings was not implemented as per #98

**Comment by trioderegion** [comment]
Two different things :)

That setting will draw the actual sight/collision lines for a given cover check.
