### ISSUE TITLE
[Feature Request] Disable "Status Effect Scale"

### ISSUE THREAD

**Issue by NdranC** [trioderegion/dnd5e-helpers#282]
Default foundry uses vertical columns to render the status effects on tokens. When I enable dnd5e helpers this is overwritten to horizontal alignment. As well as overriding other mods that alter the size of the effects (like CUBs).

Would it be possible to use dnd5e helpers without using the "Status Effect Scale"? Or at least more feature rich options to deal with it.

**Comment by trioderegion** [comment]
The main reason for this is to accommodate the Action Management HUD such that they do not overlap each other.  As you rightly pointed out, this is a bit of a hammer. I'll see if I can make this more flexible, but in the mean time, you can modify the effect scale very similarly to CUB by using the Effect Icon Scale option in Helpers.
