### ISSUE TITLE
Cover Report automaticly doesn't show up

### ISSUE THREAD

**Issue by viewho** [trioderegion/dnd5e-helpers#284]
Hello, today I installed the module and wanted to use the Cover option, I set it up everything but it doesn't work. Nothing happens when I target the enemy. I have a question about which modules DnD5e Helper doesn't work because I have about a hundred of them. When I press R it works, but I hoped it will automatically work.

**Comment by trioderegion** [comment]
I have noticed that users with tons of mods have issues with the auto cover on target. I am really not sure why, as I can't reproduce it. If you can narrow down which module is causing this, that would be helpful, but for now, I think R is going to be most reliable.
