### ISSUE TITLE
Undead Fortitude wrong DC calculation

### ISSUE THREAD

**Issue by sahneprinz** [trioderegion/dnd5e-helpers#285]
Hello there, I just created this account because I think I found a bug in the Undead Fortitude calculation. I reinstalled it but it still does the same, which is: 

When a zombie takes damage that brings it down to 0, it only takes the damage into account for the calculation that actually took all the hp out, instead of all the damage that has been rolled. Therefore:  if a zombie has 1 hp, if its enemy rolls 10 damage, only 1 of the 10 damage takes him to 0. Therefore only 1 is added to the DC 5, making it a DC 6 check. Therefore, a zombie with 1 hp will always have to roll a DC 6 regardless of the damage taken. (A zombie with 1 hp is going to be harder to take out than one with 5 hp!)

In the chat, the hp calculation would show as follows: 1-1 (10) = 0 
then: 
Undead Fortitude DC 6

Keep up the great work!

**Comment by sahneprinz** [comment]
A screenshot from the combat chat. The Zombie is at 1 hp. 
![image](https://user-images.githubusercontent.com/103567285/163172437-16c9d1bb-9793-48ef-adf5-6657265832d1.png)

**Comment by thatlonelybugbear** [comment]
FYI, that happens cause Midi will reduce the HP by only 1 as it clamps to non negative HP I think.
If you use core Foundry that works as intended.

**Comment by thatlonelybugbear** [comment]
_I am just a user of the module, so it is worth waiting for the module developer to answer!!_

**Comment by trioderegion** [comment]
If you use the "advanced saves" option for undead fort. it will prompt you for the total damage. Default is "quick saves" and it cannot account for overflow damage.

As @thatlonelybugbear indicated, the system does not account for overflow damage, so if you take 99 damage at 1 HP, then the system only see's that 1 HP change and you will get the above result.
