### ISSUE TITLE
Module incompatibilitie: Levels / Wallheight

### ISSUE THREAD

**Issue by Kurokasa** [trioderegion/dnd5e-helpers#286]
Foundry VTT ver 9
DnD 5e ver 1.5.7
Dnd5e Helpers ver 4.1.3
Levels ver 2.7.2
Wall height ver 4.2.5

Hi, the automatic cover calculation doesn´t take the wall height oder token height into account when trying to figure out if another token has cover or not, making it impossible to use the modules together since it will always get full cover from wall that are on a different floor.
It would be amazing if you could make them compatible since i love both mods. I don´t know how much work it would be but theripper93 is very active and was very helpful on his Discord. Wall height could also enable you to check if a wall is full height and should grand full cover, or just some boxes that grant half cover or some thing like that.

Thx for the awesome work :)

**Comment by trioderegion** [comment]
If I remember correctly, Levels has some sort of 3D cover checking support?

I can't say if our cover class will ever support wall height, for both technical and philosophical reasons.  However, the class is (or should be) exposed if an adventurous dev wants to contribute :) or create an expansion module similar to Kandashi's cover calculator expansion.

**Comment by Kurokasa** [comment]
Levels enables you to stack wall and tiles ontop of each other in a way that it only shows depending on the players elevation. Aka you can have a multi story building in one scene and even have fights over multiple layers.
