### ISSUE TITLE
Various features not working as intended

### ISSUE THREAD

**Issue by NateHawk85** [trioderegion/dnd5e-helpers#29]
My apologies on the reaction status automation. It appears I just needed to re-enable CUB for it to work, along with the status update. Never mind on that!

Additionally, Undead Fortitude checks seem to automatically fail if set to "Quick Saves". I checked this by reducing a zombie to 2 HP, then dealing 2 damage, and it still notified that the zombie died even though it rolled a 17 for its Constitution save.

Other than that, I love the module. Keep up the good work!

**Comment by kandashi** [comment]
I'll look into it
