### ISSUE TITLE
Attacking from behind cover

### ISSUE THREAD

**Issue by KristjanLaane** [trioderegion/dnd5e-helpers#291]
![image](https://user-images.githubusercontent.com/1708294/167211801-125fea83-4ef7-4531-85a8-7d5e402b9443.png)
If the creature attacks from behind the tree, it gets a cover penalty. But it would make sense that it can peek from behind cover and let an arrow loose if it is behind cover itself. Would be great to take that into account in cover calculations - maybe an additional option to enable attack from cover.

**Comment by trioderegion** [comment]
Double check your cover calculation method in the module's settings. Four corner vision _should_ accomplish what you are looking for.

**Comment by KristjanLaane** [comment]
Yes, I had it on Center Point Vision before. When I set it on Four corner vision, it works perfectly in the above situation. Thanks!

However, in the following situation, Four corner vision does not work:
![image](https://user-images.githubusercontent.com/1708294/167260149-6bea0617-a1c7-4938-8833-8b8c9d317205.png)
i.e. on the left the walls are Half cover, but Three-quarters cover is assigned (presumably, because the tree walls are three-quarters cover).

**Comment by trioderegion** [comment]
based on your description, yes, this is correct. If the square walls are 3/4 cover, then the final cover value should be 3/4 as the target token is completely behind the walls.

**Comment by KristjanLaane** [comment]
Ok, I understand Four corners vision better now - it does not fully do what this post is about, which is attacking without any penalty if the attacker is behind cover. 

This situation highlights it best:
![image](https://user-images.githubusercontent.com/1708294/167287589-141f7eff-61c8-48e3-96fd-9c96f02eacf7.png)
3/4 cover is applied in this case and it would be great to have **an option in settings** so that no cover is calculated for the attacker behind the tree cover. Because it makes sense that the attacker can peek out of cover, and shoot - the attacker is using cover as protection, but it should not hinder it in attacking.

**Comment by trioderegion** [comment]
In that case, you want to make the tree's square walls slightly smaller to represent being able to look around them.  That said, this is why we show the cover buttons even on automatic application, so you can override our guess based on your game's situation.
