### ISSUE TITLE
[Issue] Uncaught (in promise) TypeError: Cannot read properties of null (reading 'drawShape')

### ISSUE THREAD

**Issue by Krigsmaskine** [trioderegion/dnd5e-helpers#296]
Hi,

When running a mutate macro with Warpgate, I get this error from dnd5e helpers - I actually don't know the consequence of it, I don't even think I have ActionManagement enabled at all.

```js
SmoothGraphics.ts:526 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'drawShape')
[Detected 1 package: dnd5e-helpers]
    at SmoothGraphics.drawShape (SmoothGraphics.ts:526)
    at SmoothGraphics.drawRoundedRect (SmoothGraphics.ts:475)
    at Token5e.Token._drawEffect (ActionManagement.js:429)
    at async Promise.all (index 1)
    at async Token5e.drawEffects (foundry.js:38383)
```

**Comment by trioderegion** [comment]
You should be able to ignore this. Helpers is a bit aggressive with its ability to rescale token status icons. In the next revision, I'll get it to play more nicely.

That said, try increasing the delay in warpgate's module options. It can sometimes fix these drawing errors.

**Comment by trioderegion** [comment]
Having a hard time reproducing this after a bit of a rework to that code. Please re-open this ticket if you see this again after 4.2.0. Thank you ❤️
