### ISSUE TITLE
Support Localization

### ISSUE THREAD

**Issue by drdwing** [trioderegion/dnd5e-helpers#31]
There is some difficulty in using this module for non English users.
I know this module is awesome but can't use it perfectly 😢

**Comment by trioderegion** [comment]
I hear you. Particularly now that more options and chat messages are being produced. I will look into it <3

**Comment by drdwing** [comment]
> I hear you. Particularly now that more options and chat messages are being produced. I will look into it <3

Thank you!!

**Comment by trioderegion** [comment]
French localization has been requested by @Elfenduil.

**Comment by kandashi** [comment]
@Elfenduil the localization branch is here if you want to start working on a translation https://github.com/trioderegion/dnd5e-helpers/tree/localization

**Comment by trioderegion** [comment]
included in 1.9.0
