### ISSUE TITLE
Legendary Actions Not Restoring

### ISSUE THREAD

**Issue by PlutoHimself** [trioderegion/dnd5e-helpers#32]
I was using three homebrew creatures all with legendary actions. On their turn, it appeared to restore them, then it would consume all 3 when I next used an LA. Or, sometimes, it wouldn't restore it at all on their turn. Managing 3 LA creatures was a little complicated, so I can't really provide more information - I tried to pay attention to it happening, but couldn't figure out the trigger or predict it. 

SO besides just telling you this is something I noticed, is it possible to put in console messages or some kind of error log so that I can try and get more data?

**Comment by kandashi** [comment]
I'll have a look at this later today, if you notice this happening you can open the console with f12 and see if anything pops up in red

**Comment by PlutoHimself** [comment]
Well, that was kind of what I was asking for. I didn't see anything in the console log, so even a confirmation message that a legendary action has been restored (and possibly used?) could help me identify when exactly in the order of turns and actions it occurred. 

Given 2 creatures, LA1 and LA2, I can say, thinking back, I noticed LA1 be restored on its turn. Then LA2 would take its turn next in the order, get back its LAs, then at the end of LA2's turn I would open LA1's sheet to use an LA and they would be at 0.  I cannot tell you if this happened every time, but that is as close to my workflow as I can give you to try and replicate it.

**Comment by kandashi** [comment]
Just have to check, they weren't linked actors?
Im sure we can add in a ui notification of the reset however.

**Comment by trioderegion** [comment]
Any fixes for this won't make it into 1.8.1, but I will add a notification when the leg. action is restored in 1.8.1. Should help isolate any workflow issues.

**Comment by PlutoHimself** [comment]
> Just have to check, they weren't linked actors?

they were not, and that's something I should probably fix as a point of design (as they're named npcs). but as I was using them, no, they weren't. 

> Any fixes for this won't make it into 1.8.1, but I will add a notification when the leg. action is restored in 1.8.1. Should help isolate any workflow issues.

That would be great, thanks! Maybe a verbose/terse toggle in case people don't want the notifications or console notes every time something is gained/lost.

**Comment by PlutoHimself** [comment]
Okay, I did some more testing, and the notification was very helpful. The first thing I noticed is that the LAs would reset on the character sheet, but NOT the resource bar that's set up to track them. Also, when Character A didn't use all possible LAs, after recharging, Character A would use any action (not an LA) on its turn but then the LA count would reset to its _previous_ value on the character sheet. Character B's LAs seemed to reset just fine, but the resource bar never changed either (I had like two dozen animals to keep track of in this fight, so I am reasonably sure but not 100%). 

I would be happy to invite you (someone) into the game and run through a "combat" so you can see it in action, if you want.

**Comment by kandashi** [comment]
The first thing I noticed is that the LAs would reset on the character sheet, but NOT the resource bar that's set up to track them.

them.

-I believe this is a bug with pre 7.9 foundry

As for the other thing that is very odd as it should only ever reset to the max value. If you could invite me at some point that would be good

**Comment by trioderegion** [comment]
There is a clash with reaction management and legendary action resets. Thanks for the followup. I've reproduced what i think to be the issue:

1) Have any creature with a leg. act. use an action off turn (consumes reaction and status is applied).
2) Have that creature use one or more legendary actions.
3) On that creature's turn, the reaction status gets reset, but it also blocks the reset of the legendary action, despite the message saying it was reset.

**Comment by trioderegion** [comment]
This issue is fixed in 1.8.4. Please let us know if it still persists.

Thanks for the report.
