### ISSUE TITLE
dnd5e 1.2.0 implements Proficiency Helper

### ISSUE THREAD

**Issue by akrigline** [trioderegion/dnd5e-helpers#35]
[From the changelog](https://gitlab.com/foundrynet/dnd5e/-/releases/release-1.2.0)

> Updated the logic which assigns proficiency to new Owned Items to reference the weapon and armor proficiencies of a player character to make a dynamic choice about the initial proficiency value for the weapon or equipment.

I haven't tested thoroughly but this might mean that this module can disable its own logic surrounding this functionality if the active system is equal or greater than 1.2.0

**Comment by trioderegion** [comment]
Wonderful. Thanks a lot for the heads up. Will investigate!

**Comment by kandashi** [comment]
It seems the core system dosnt handle tools yet, so we will keep that implementaion in and remove the rest if needed

**Comment by akrigline** [comment]
Created an issue for that in the Gitlab:

https://gitlab.com/foundrynet/dnd5e/-/issues/883

Thanks for your investigations guys.

**Comment by trioderegion** [comment]
After some investigation. Helpers can still attempt to match specific weapon proficiencies (i.e. "Daggers") and Tools, which core 5e lacks.

It also prompts me to address the Daggers proficiency not matching to the Dagger item (as an example) in Helpers, however. I think the helpers code, after that, could be a direct replacement, but the structure is different enough for me to want take more time doing so.
