### ISSUE TITLE
Support cover bonuses or chat reminders for cover

### ISSUE THREAD

**Issue by kandashi** [trioderegion/dnd5e-helpers#42]
sdenecToday at 3:39 PM
How exactly does the cover feature of dnd5e helper work? If I set tokens as interfering I do get a message for half cover but it doesn't seem to affect the roll or AC of the target ... can someone explain?
Kandashi (He/Him)Today at 3:40 PM
it is currently jsut a chat popup, we might be adding effects to rolls in the future
sdenecToday at 3:41 PM
Ah, check! If it stays a pop up at least I would really appreciate a reminder of the AC bonus. +2 for half cover? :sweat_smile:
Kandashi (He/Him)Today at 3:42 PM
the issue is that different DMs rule cover differently
sdenecToday at 3:42 PM
oh, alright then :wink:
Kandashi (He/Him)Today at 3:42 PM
ill put it as something to work on

**Comment by trioderegion** [comment]
A reasonable request and falls in line with the RAW implementation cover and line of sight.

half = +2 to ac and dex saves
3/4 = +5 to ac and dex saves

Will add to the docket! Note, as Kandashi indicated, it will be feedback only for the time being (no automation).

**Comment by trioderegion** [comment]
A small reminder is included in 1.8.6.

Considering automation options for 1.9.0

**Comment by kandashi** [comment]
Added in 1.11.0
