### ISSUE TITLE
Feature Request: Wound Trigger by Size

### ISSUE THREAD

**Issue by DivertedCircle** [trioderegion/dnd5e-helpers#46]
In my campaign we use a rule where being reduced to 0 hit points by an attack from a huge or larger creature causes a character to suffer a wound. This can be partially duplicated with the currently available settings, but rolls anytime a character hits 0 hit points rather than only when done so by an attack from a huge or larger creature. Being able to restrict the trigger from firing based on the size of the attacker would be fantastic.

**Comment by kandashi** [comment]
This is not really possible as you cannot tell which damage source was the one to down a character, only that it hit 0
