### ISSUE TITLE
Add Translation French ?

### ISSUE THREAD

**Issue by Elfenduil** [trioderegion/dnd5e-helpers#47]
Hello,

Would it be possible to include French translations if I provided a file?

Thank you

**Comment by trioderegion** [comment]
Localization is slated for the refactor version of 2.0.0. I cannot promise a fast turnaround, but localization is the next major feature to be added. See #31 and follow progress there :)

**Comment by trioderegion** [comment]
Reopening as we have gotten a spanish language translation merge request!

You can find our en.json in the "localization" branch. If you can provide a french translation file, we will absolutely pull it in for the localization release!

**Comment by Elfenduil** [comment]
Hello,

In Att, the file translate in French.

Thank you
[fr DnD5Helpers.txt](https://github.com/trioderegion/dnd5e-helpers/files/5847728/fr.DnD5Helpers.txt)

**Comment by trioderegion** [comment]
Thank you! Will get this integrated into our release and will have some
time to work on it this weekend :)

**Comment by trioderegion** [comment]
Included in 1.9.0
