### ISSUE TITLE
Feature Request: Hide NPC names in chat

### ISSUE THREAD

**Issue by giogreymon** [trioderegion/dnd5e-helpers#48]
A way to hide/mask/change NPC names from Player view of chat when: 
1. an NPC checks for any cover 
2. When a PC checks their sightline to NPC 

Something from "Vampire checks their sightline to Zanna" --> "Creature checks their sightline to Zanna"; or completely removed from PC view

**Comment by trioderegion** [comment]
Reasonable request. Will explore solutions for 1.9.0

**Comment by trioderegion** [comment]
Implemented in 1.8.8
