### ISSUE TITLE
Consider PC ability to ignore half/cover when auto-calculate comes

### ISSUE THREAD

**Issue by giogreymon** [trioderegion/dnd5e-helpers#49]
This is a small thing for when you eventually add automatically calculating cover bonuses. The ability to recognize a PC has **sharpshooter**/**spell sniper** feat or similar effects. It might need to be hooked on to a midi flag or create a new one entirely so more complicated than it seems (at least to me)

**Comment by kandashi** [comment]
That shouldn't be too hard no

**Comment by trioderegion** [comment]
These are the reasons I'm hesitant to add AC automation 😅 .

It may be better for me to work on the API so modules that *do* provide automation can leverage this functionality.

**Comment by kandashi** [comment]
Added in 1.11.0
