### ISSUE TITLE
Support for detecting crits in Great Wound workflow with midi QOL rolling system 

### ISSUE THREAD

**Issue by dirusulixes** [trioderegion/dnd5e-helpers#52]
DnD5e 1.2.2, Midi QOL  0.3.50 and DnD5e Helpers 1.8.6 (no other modules enabled)
With roll automation support enabled in midi, the open wounds table roll triggers and works fine for death saves and 0 HP, but not for critical hits.

Disabling roll automation support the table roll on crits works. I would be nice to have support for modules like midi QOL that change the rolling system.

**Comment by trioderegion** [comment]
Thank you for the suggestion. I will have to leave the decision to support Midi-QOL to @kandashi as I do not use any rolling modules, personally.

**Comment by kandashi** [comment]
I will look at it but make no promises. Its not a high priority issue in the end
