### ISSUE TITLE
Great Wound socket fails to receive

### ISSUE THREAD

**Issue by trioderegion** [trioderegion/dnd5e-helpers#53]
As of 1.8.7, the great wound roll socket is emitted, but does not appear to be received.

**Comment by trioderegion** [comment]
Update: Original reporting user found it to be a bad interaction with Better Tables.

Uncertain how I reproduced this. May be sleepy -_-.

**Comment by kandashi** [comment]
I cannot seem to preproduce, with better tables with several permutations

**Comment by trioderegion** [comment]
Going to close this issue. If the problem presents itself again, please open a new one :)
