### ISSUE TITLE
Feature Suggestion: Support 5/10/5 rule for templates

### ISSUE THREAD

**Issue by MSAbaddon** [trioderegion/dnd5e-helpers#54]
The way templates are implemented in Foundry does not match the DnD5e 5/10/5 distance rules. Would be great if the module would also offer an option to convert templates using the 5/10/5 distance rules.

**Comment by kandashi** [comment]
That's basically what the standard foundry template do is it not?

**Comment by MSAbaddon** [comment]
Unfortunately not, here some examples:

![image](https://user-images.githubusercontent.com/66370966/104843409-cb288300-58ca-11eb-9ba5-340dfc174322.png)

**Comment by kandashi** [comment]
I agree about the cones (but that's just angle not range,  and the sphere one seems accurate (not the red line version)

**Comment by kandashi** [comment]
![Screenshot_20210117-131833_Chrome.jpg](https://user-images.githubusercontent.com/1347785/104844185-97e3f500-58c6-11eb-82af-9429ff8734b2.jpg)
You can see here how you can get to this square with 20ft of movement using 5/10/5

**Comment by MSAbaddon** [comment]
Regarding the circle - the point of origin is a square corner. If I start counting from the actual point of origin reaching the top left corner of the squares results in a distance of 25 feet.

**Comment by kandashi** [comment]
How? It's still 20ft ![Screenshot_20210117-134414_Chrome.jpg](https://user-images.githubusercontent.com/1347785/104844795-1db56f80-58ca-11eb-9053-95022b48d91c.jpg)

**Comment by kandashi** [comment]
But tokens can't occupy grid corners, with your method it only takes 15ft of movement to leave the area no matter where you are, it actually makes these less effective

**Comment by MSAbaddon** [comment]
Hm, that's actually a good Point, didn't consider this - thanks for the clarification :-)
Still, cones are somewhat problematic.

**Comment by kandashi** [comment]
I would use the standard cones from 5e helpers, I find those are pretty much correct

**Comment by trioderegion** [comment]
The 5/10/5 rule is actually harder to adjust templates for due to the quantization error between grid squares vs linear distance. And increasing the cone angle on diagonals will drastically overshoot the proper number of covered squares (cones are as long as they are wide at any point).

Thank you for the concern, but this one is a wont-fix. Happy gaming.
