### ISSUE TITLE
Undead Fortitude - DC seems to be incorrect

### ISSUE THREAD

**Issue by RavenknightDM** [trioderegion/dnd5e-helpers#56]
Hiya,
I don't think that the Undead Fortitude DC is being calculated 5+damage delivered.

**Comment by kandashi** [comment]
If you turn the debug setting on it should show the dc, iirc

**Comment by kandashi** [comment]
From going through again I cannot confirm this, examples would be good

**Comment by RavenknightDM** [comment]
Hi again, sorry for not providing examples above. In either case I spent the evening reinstalling all my modules and now it seems to work just as intended so whatever problem I had was with my setup and not your mod. Before I updated no damage would register no matter what I put in the "damage-taken" question.
Sorry for taking up your time, Kandashi. The module is a great help for me and I was so bummed that it didn't work that I posted before thinking. :/
/Ravenknight

**Comment by kandashi** [comment]
No problem, glad it works 🙂
