### ISSUE TITLE
Cover Check triggered by specific key or combination of key + mouse click

### ISSUE THREAD

**Issue by thatlonelybugbear** [trioderegion/dnd5e-helpers#61]
Could the cover check be triggered only on demand, eg. by a keystroke or combination and not every time someone selects a target? Will clear up the chat a bit as there are times that it is not necessary and/or difficult to implement correctly on maps with many walls used for pillars and such!

**Comment by trioderegion** [comment]
Hotkeys and UI elements are uncharted territory for me, but, your suggestion is a reasonable one. Can't promise a fast turnaround, but I'll put it on the docket.

In the mean time, you can disable the auto cover calc and call `token.computeCover` to do a "manual" cover check from a macro.

**Comment by thatlonelybugbear** [comment]
Cheers! Good point to use the macro in the meantime ;)

**Comment by kandashi** [comment]
Added in 1.11.0
