### ISSUE TITLE
Request: track actions and bonus actions during combat

### ISSUE THREAD

**Issue by pcwilcox** [trioderegion/dnd5e-helpers#73]
It would be helpful (especially for newer players) if the module notified them in some way that their action/bonus action was used.

**Comment by trioderegion** [comment]
Reasonable request. Will look into it post v2.0 release.

Only concern off the top of my head is the number of status icons I would be applying...but maybe there is a different approach.

Thanks for the suggestion :)

**Comment by kandashi** [comment]
Maybe a single status with different permutations of combinations, or a Pixi element above the token image

**Comment by trioderegion** [comment]
mmm, a PIXI element would be a good excuse to pull that stuff in 5e Helpers. I like it :)

**Comment by kandashi** [comment]
What icons would work well for this?

**Comment by kandashi** [comment]
Will be avaliable in 1.11.0
