### ISSUE TITLE
Feature: Lair Actions Pop up

### ISSUE THREAD

**Issue by trioderegion** [trioderegion/dnd5e-helpers#74]
On turn change, check current init and previous init to decide if its the Lair's turn.

Scour current combatant list (bleh) for lair action items and populate a dialog with item.roll() callbacks.

**Comment by kandashi** [comment]
I can work on this, I would suggest instead hook on createCombatant (or whatever its called) and check for lair actions and add to a map stored globally, or on the combat itself.

**Comment by trioderegion** [comment]
Flagging info on the combat itself sounds like the right approach. It would
allow us to manage multiple combats easier :stress:

**Comment by kandashi** [comment]
Will be avaliable in 1.11.0

**Comment by kandashi** [comment]
Adding Legendary Action management to this too.
