### ISSUE TITLE
Minimum result modifier does not work well with reroll modifier

### ISSUE THREAD

**Issue by jflevesque** [trioderegion/dnd5e-helpers#81]
I have a player which has Flames of Phlegethos and Elemental Adept feats, which means that it rerolls 1, but has minimum of 2 if both rolls are ones.

I tried the following formula for Firebolt for example: /r 1d10r1mr2, but when the system rerolls the 1, it seems to roll, 4 times instead in total. (For testing purposes, I used 1d2 instead of 1d10 to trigger the issue quicker).

**Comment by trioderegion** [comment]
That was an unexpected interaction. I believe I have fixed it locally.
![image](https://user-images.githubusercontent.com/14878515/113148164-893b8780-91ff-11eb-8610-0b18a13a837b.png)

Will continue testing and get a release out in a few days. Thank you for the report :)

In the mean time, you can patch line 308 if you are feeling bold.

Original: `if (result.result < min) {`

Fixed: `if (result.result < min && result.active) {`

I was not paying attention to whether a die roll had been discarded for any reason and was making sure *all* dice rolled were a minimum value -- whoops!

**Comment by trioderegion** [comment]
The PR slipped through the cracks -- will get this published asap.
