### ISSUE TITLE
Feature Request: Legendary Action/Resistance Prompts

### ISSUE THREAD

**Issue by DivertedCircle** [trioderegion/dnd5e-helpers#83]
Note sure it's possible, but I'd love to see prompts added to use both Legendary Actions and Legendary Resistances if charges are available. Legendary Resistances would be prompted any time the creature fails a save (or is forced to make a save if that's easier) and Legendary Actions would be at the end of another creatures turn.

**Comment by trioderegion** [comment]
It would be possible to utilize the upcoming Lair Actions features to do a similar thing for Legendary Actions.

The legendary resistance is a bit harder due to the disconnect between something forcing you to make a save, and the resulting roll of the save.

**Comment by kandashi** [comment]
Added for legendary actions in 1.11.0
