### ISSUE TITLE
Feature Request: Wild Magic Barbarian

### ISSUE THREAD

**Issue by nulmas** [trioderegion/dnd5e-helpers#85]
Hey there!

I've been trying to implement some of the features of a Wild Magic Barbarian in my game, and I remembered that DnD5e Helpers has an automatic table for Sorcerer Wild Surges. That got me wondering: would it be possible to add a second table that would trigger whenever a Wild Magic Barbarian rages?

**Comment by trioderegion** [comment]
Triggering a table draw on use of a feature is well within the scope of a simple macro or Item Macro.  There is little need to 5e Helpers to handle this explicitly.
