### ISSUE TITLE
Feature Request: Hide NPC name for Open/Great Wound saves

### ISSUE THREAD

**Issue by ditzer252** [trioderegion/dnd5e-helpers#87]
Similar to the way you have sanitized NPC names for cover checks, can you sanitize the NPC names when sending results of saving throws to the chat?  Thanks for considering this request!

**Comment by ditzer252** [comment]
Or perhaps use the token name, which may be hidden by CUB in certain conditions?

**Comment by trioderegion** [comment]
I need to review the code flow for those features to make sure its possible, but its a reasonable request.

**Comment by hugoprudente** [comment]
Feature will be available from 1.11.0 forward :) Thanks for the suggestion, resolving.
