### ISSUE TITLE
Tokens with a wall behind/beside them receiving cover.

### ISSUE THREAD

**Issue by RogueEntityX** [trioderegion/dnd5e-helpers#90]
This may be related to the hitbox problem in Issue #79.

I've found that when using the cover calculator, whether centerpoint or 4 corners, if the target is adjacent to a (Foundry) wall, they receive cover, even when that wall is *behind* the target, and not intervening.

For example, in the following case, you can see that Perrin is being calculated as having half cover when targetted by Morthos:
![image](https://user-images.githubusercontent.com/72455534/115160076-4b928780-a064-11eb-8ae7-ba57d171afc3.png)

And again, Perrin is calculated as 3/4 cover when in this corner:
![image](https://user-images.githubusercontent.com/72455534/115160113-83013400-a064-11eb-8aea-ba813f744eb6.png)

If I use Shift to drop Perrin even a hairs breadth away from the wall, he gets no cover. I understand that one solution could be to offset the walls as I wall my maps, but I think in general, people tend to wall along grid lines, and many premade scenes from content developers tend to be walled along grid lines already.

**Comment by trioderegion** [comment]
You are correct, this is the same issue as #79 and is a common walling configuration.

I'll elevate the priority on this one as it is starting to cause issues and we have upcoming features that will lean more heavily on our cover system :)

Thank you for the report and screen shots.
