### ISSUE TITLE
Reaction management doesn't work with icons from world script

### ISSUE THREAD

**Issue by benbarbour** [trioderegion/dnd5e-helpers#92]
I used a world script to replace all the status icons, like so: https://foundryvtt.wiki/en/basics/world-scripts. I have one called "Reaction Used", but dnd5e-helpers can't find it. Pretty sure it's because the name of the condition label is not localized.

From playing in the console quickly, I think that `GetStatusEffect` could be easily modified to find my effect by searching for an exact match. Something like:

```
let statusEffect = CONFIG.statusEffects.find(st => st.label === `EFFECT.${statusLabel}` || st.label === statusName);
```

Or maybe you only want to do an exact match if `statusLabel` is `undefined`, as it is in my world.

**Comment by trioderegion** [comment]
1.11.0 Will address this issue with some fancy new functionality! Stay tuned!
